### ISSUE TITLE
90 degree rotation request

### ISSUE THREAD

**Issue by DrewCipher505** [bigtreetech/BIGTREETECH-TFT35-V3.0#101]
Creality Ender 3 v2, CR-6, and other printers have a form factor with  90 degree vertically oriented control screen.

Please add capability to define a 90 degree orientation along with applicable graphics and functionality including but not limited to encoder navigation and touch navigation

**Comment by adelyser** [comment]
You are posting in the wrong repository. This repository is for the TFT35-v3.0 hardware. Software is located at: [TouchScreenFirmware](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware)

**Comment by DrewCipher505** [comment]
Thank you
