### ISSUE TITLE
I've already downloaded correct files to the screen and updated it. What else do I do?

### ISSUE THREAD

**Issue by jayala1213** [bigtreetech/BIGTREETECH-TFT35-V3.0#103]
I've already downloaded correct files to the screen and updated it. What else do I do?
Im using a skr 1.4 turbo board. 

![image](https://user-images.githubusercontent.com/74276786/102725135-a80db200-42d1-11eb-9d96-5272e720a7f5.jpeg)

![image](https://user-images.githubusercontent.com/74276786/102725155-c96e9e00-42d1-11eb-9360-fe5c322f9e5f.jpeg)

__Originally posted by @jayala1213 in https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/issues/102__

**Comment by oldman4U** [comment]
You should tell the whole story - that it has been working and what you did - before asking for help. Opening one ticket after the other will not solve the problem.;-(
