### ISSUE TITLE
Screen shows unknown command "image of square box"

### ISSUE THREAD

**Issue by RetArsonFD** [bigtreetech/BIGTREETECH-TFT35-V3.0#105]
I couldn't figure out how to put a pic of a square box in the text, so I had to spell it it out...but it's in the " marks on the screen.  What does this mean ??

**Comment by oldman4U** [comment]
Hi.

Maybe you can attach a picture or a movie which shows the issue?

**Comment by RetArsonFD** [comment]
> Hi.
> 
> Maybe you can attach a picture or a movie which shows the issue?

Thank you for replying, and attempting to help me out.  However, I figured out what the error was.  Somehow I had a limit switch unplugged.  FWIW, this board is pretty intimidating to a new person.  It has WAAAAY more functions than I know what to do with, and I probably haven't even found all of them yet.  lol.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
