### ISSUE TITLE
"Print From Media"

### ISSUE THREAD

**Issue by Jhawk255** [bigtreetech/BIGTREETECH-TFT35-V3.0#107]
Since I installed a new SKR mini 3 v2 and a TFT35-3 V3.0, my "print from media" option is missing from the LCD12864 Simulator. I can print from the touch screen but not the simulator. I put my old display board back on and it is not there also. It used to work just fine. Im suspecting a problem with the SKR Mini 3. anyone else have this issue ?

**Comment by oldman4U** [comment]
Hi

You have to enable sdprint in Marlin which is off by default.

**Comment by Jhawk255** [comment]
Is that done from the screen or do I have to enable it in the firmware ?
Thanks !

**Comment by oldman4U** [comment]
Firmware of the mainboard.

Jhawk255 <notifications@github.com> schrieb am So. 3. Jän. 2021 um 16:00:

> Is that done from the screen or do I have to enable it in the firmware ?
> Thanks !
>

**Comment by Jhawk255** [comment]
Thanks for your reply. That doesn’t make sense to disable that function by default. How are you supposed to print unless you flash the motherboard ? Anyway, I’m unable to flash my motherboard (it’s a new upgrade) and will not read the cf card. I have a replacement board coming tomorrow. Hopefully I’ll have better luck.

**Comment by oldman4U** [comment]
Thats something you should ask those responsible for Marlin in the Marlin
repo.


Jhawk255 <notifications@github.com> schrieb am So. 3. Jän. 2021 um 18:59:

> Thanks for your reply. That doesn’t make sense to disable that function by
> default. How are you supposed to print unless you flash the motherboard ?
> Anyway, I’m unable to flash my motherboard (it’s a new upgrade) and will
> not read the cf card. I have a replacement board coming tomorrow. Hopefully
> I’ll have better luck.
>

**Comment by oldman4U** [comment]
How is the replacement working?

**Comment by Jhawk255** [comment]
Seems to be working fine !!! Now I just need to find the proper firmware to
install my BLTouch V3.1

Thanks

**Comment by oldman4U** [comment]
Cool.

Happy printing 

Please help the community and close the ticket once you do not need it anymore. Thank you
