### ISSUE TITLE
Custom Icons dosent change on TFT35 V3

### ISSUE THREAD

**Issue by Charlyw204** [bigtreetech/BIGTREETECH-TFT35-V3.0#11]

**Comment by Charlyw204** [comment]
Try to change the icon follow the steps from the how to but the icons and boot logo dosent change.

save as 16 bit and bmp with 95x95 pixel

**Comment by cristerg** [comment]
Make maps on SDCard
\TFT35\bmp
and
\TFT35\font
Worked for me

**Comment by bmxorcist** [comment]
> Make maps on SDCard
> \TFT35\bmp
> and
> \TFT35\font
> Worked for me

YESS!!!! That worked for me too!  Thanks!

**Comment by oldman4U** [comment]
Hi.

Could you please close this ticket. Seems the reported issue has been fixed for almost a year now.

Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
