### ISSUE TITLE
No control once installed.  Display is on but no control.

### ISSUE THREAD

**Issue by steveandpeggyb** [bigtreetech/BIGTREETECH-TFT35-V3.0#113]
I am trying to install the new (to me) TFT35-E3 v3.0 display.  The display comes on, and I have the two options of Marlin mode or Touch mode.  However, it does not recognize my touch or the control knob.  I cannot get anything to work.  If I put my old factory display on, things seem to work.  I have the BTT SKR Mini V2.0 install and now installing the TFT touch screen.  

I've swapped three different ribbon cables to no avail.

Any thoughts?

Thanks,
Steve

**Comment by oldman4U** [comment]
Wrong repository for the E3 TFT.

Read the readme on the front page of the firmware repository for how to reset the TFT.

**Comment by steveandpeggyb** [comment]
Sorry, missed that but solved the problem with nylon washers.
