### ISSUE TITLE
Unable to preview PrusaSlicer gcode

### ISSUE THREAD

**Issue by ironman977** [bigtreetech/BIGTREETECH-TFT35-V3.0#114]
Hi, I turned off File List in menu but I can't see the preview of my gcode generated by PrusaSlicer 2.3.0, what can I do?

**Comment by oldman4U** [comment]
You can use a slicer which is supported like Cura. Check the corresponding ticket in the firmware repository and close this ticket here because it has nothing to do with the hardware.
