### ISSUE TITLE
Tft35 mode probe points off 

### ISSUE THREAD

**Issue by howie141011** [bigtreetech/BIGTREETECH-TFT35-V3.0#116]
I recently flashed new update for tft35 but after I set everything the probe point when probing corners are all off, but when in marlin mode it’s perfectly fine .

**Comment by oldman4U** [comment]
And you set the correct bed size and probe offset in config.ini?

**Comment by oldman4U** [comment]
Any news?

**Comment by howie141011** [comment]
Yes I did everything but found an issue . The new master firmware has 3 separate firmware files for the tft35 I accidentally flashed the one with a b in front . After I flashed the other I'm all set

**Comment by oldman4U** [comment]
Sounds great 

Please help the community and close the ticket once you do not need it anymore. Thank you 

Happy printing
