### ISSUE TITLE
TFT35V3 with SKR1.3, LCD12864 is not working.

### ISSUE THREAD

**Issue by Thamone** [bigtreetech/BIGTREETECH-TFT35-V3.0#12]
I have connected EXP1 to EXP1, EXP2 to EXP2 and TFT cable.
Resulted in touch mode working OK but LCD12864 only show "LCD12864 Simulator" on top of screen, nothing else. I can still switching between 2 mode. [https://photos.app.goo.gl/sngJyQcUzmGJ7Tcn9](url)

I have tried connected EXP1 on SKR into EXP3 on TFT35, now every thing works LCD12864 show every menu. But if I press reset button or switch off printer and back on the screen go black cannot do anything. I need to unplug EXP1 cable and reconnect it again to make it back to work again. [https://photos.app.goo.gl/G7FNPFoLU4RoAMkJ7](url)

**Comment by seans883** [comment]
We're you able to figure this out? I am having the exact same problem right now.
