### ISSUE TITLE
"No printer attached!" Error with btt SKR 1.4 Turbo - rerun

### ISSUE THREAD

**Issue by whiney1** [bigtreetech/BIGTREETECH-TFT35-V3.0#120]
Hi - I've got a problem trying to connect to this TFT that I can't fix. 

**My setup:**

- BTT SKR V1.4 Turbo
- Marlin 2.0
- BTT TFT35 V3.0

**Symptoms:**

- Marlin mode works
- Touchscreen mode does not work 'No printer attached!' - No hotend data, no commands work, etc.

**Things I've tried:**

- Ensuring SERIAL_PORT(s) and baud rate are set in Marlin. I've tried 0/-1, -1/0. Baud is 115200
- Ensuring serial on TFT is 115200
- Ensuring SDSUPPORT is defined
- Trying 250000 and 57600 baud rate (matching Marlin and TFT each time)
- checking cable continuity from TFT board pins to SKR pins (no issues)
- Checking continuity on TFT pins between themselves (there is another issue that said there is a dodgy batch of TFT with internal shorts)
- switching Rx/Tx wires to see if there was a mismatch
- Compiling my own TFT firmware and flashing it (source downloaded today)
- Checking notes in TFT config.ini to make sure Marlin setting align

**Weird behaviour:**
I use Repetier normally. When I have everything configured properly, and I connect with Repetier on my PC, the TFT starts continuously beeping. You can see during this beeping that the hotend temperature actually displays on the screen but it is unresponsive until you reset it. Status shows an error 'echo:' or similar but it flashes so is hard to read and seems to be cut off.
Interestingly, when I connect with Pronterface, there are no errors.

This makes me think that the TFT/board is physically configured correctly, but that there is some issue with the serial ports configuration. But it has me stumped. Any ideas?

TIA

**Comment by whiney1** [comment]
If it matters, I am running a delta printer with TMC2209 drivers and sensorless homing, and a knock-off BLTouch.

**Comment by radek8** [comment]
If you send a command from Pronterface
M503
M115
M114

Does TFT connect?

**Comment by radek8** [comment]
send Marlin and TFT configuration files

**Comment by whiney1** [comment]
Nope, still says 'No printer attached!'. 
Interestingly, M115 only works about half the time. Sometimes it just stays on 'SENDING:M115' with no response, send it again and it outputs properly. 

Appreciate you taking the time to answer!

The TFT config has baud at 250000 but I've had it at 115200 for most of testing. And I make sure to set it to whatever is in Marlin each time.

[Marlin and TFT config files.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/6087275/Marlin.and.TFT.config.files.zip)

**Comment by radek8** [comment]
You have different serial port speeds in the included configuration files.

Set 115200 in both configurations
Once the device is communicating with each other, you can try to increase the speed.

**Comment by radek8** [comment]
It looks like a faulty serial port pin on the SKR or TFT connector.
Want to try another port?
It has happened several times that the RS232 connector on the TFT was defective

To test, disconnect the RX and TX pin of the SR232 cable to the TFT and connect them to the RX and TX pins on the UART3 connector.
To do this, you need to upload the modified FW to the TFT
[BIGTREE_TFT35_V3.0.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/6093274/BIGTREE_TFT35_V3.0.26.x.zip)

**Comment by DevilsDJ1990** [comment]
Hi I am using the SKR 1.4 Turbo and TFT.35 E3 V3 and Im having the same issue. I am currently making a custom machine of my design and was wondering a lot about what board to use - Lerdge K or this one and decided on this one. 
I am a total noob at programming , this was my first attempt at Marlin , so far I've only been using the stock firmware's on my printers.
So far I've tryed serial ports 0/-1 , -1/0 , baudrate 115200 , 250000 making sure its the same on both TFT and board. I installed a few different versions on the TFT and I think I am using the latest one now , also using marlin 2.07
The last thin after reading this post was trying what @radek8 said about disconnecting the RX and TX cables from the RS323 and connecting them on the UART3 and uploading the modified firmware he provided and still nothing.
Forgot to mention in Marlin mode everything works (now after 10 hours ) but still No Printer Attached on TFT mode.
Im attaching my config files for board and TFT(or at least I think this was the last one I used)
[Marlin and TFT config.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/6097652/Marlin.and.TFT.config.zip)

**Comment by DevilsDJ1990** [comment]
Here is how I have connected the TFT to the board as @radek8 mentioned 
![IMG_20210307_194519](https://user-images.githubusercontent.com/80215885/110249258-0582d800-7f7e-11eb-87e2-56aae08c3adc.jpg)
![IMG_20210307_194537](https://user-images.githubusercontent.com/80215885/110249259-06b40500-7f7e-11eb-9f8b-e4c79f51c357.jpg)

**Comment by DevilsDJ1990** [comment]
Just now downloaded this [https://github.com/radek8/BIGTREETECH-TouchScreenFirmware](https://github.com/radek8/BIGTREETECH-TouchScreenFirmware) , and put from folder "Copy to SD CARD" - config.ini , BIGTREE_TFT35_V3.0_E3.26.x.bin , language_en.ini , and the TFT35 folder from THEME_Unified Menu Material theme to and SD card and inserted it on the TFT waited to do it's thing , put cables and original pin locations and still nothing.

**Comment by radek8** [comment]
You have it badly connected

![image](https://user-images.githubusercontent.com/46979052/110252305-108d3680-7f85-11eb-934a-6164d51602a8.png)

**Comment by radek8** [comment]
There is often a problem with the serial cable.
First of all, measure if the cable is OK.

**Comment by DevilsDJ1990** [comment]
@radek8  Yeah I noticed , but after I updated with  https://github.com/radek8/BIGTREETECH-TouchScreenFirmware I cant use the bin file you posted here , can you possible modify one for the E3 version for me as so far I have no idea on how to compile one in VSCode for the TFT , barely managed to compile one for MArlin for the board. Also tried 2 different cables , the one you see in the photo and the stock one that came with the board and tft

**Comment by radek8** [comment]
[BIGTREE_TFT35_V3.0_E3.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/6097826/BIGTREE_TFT35_V3.0_E3.26.x.zip)

**Comment by DevilsDJ1990** [comment]
@radek8 Thank you alot , so now I do this right and just put all of these on an SD card and into the TFT
![Untitled](https://user-images.githubusercontent.com/80215885/110252715-6cf55380-7f8f-11eb-9e41-83022ad50a03.jpg)

**Comment by radek8** [comment]
Yes and restart the display

**Comment by radek8** [comment]
Be careful you have the old date on other files.
Instead, download the current one.

**Comment by DevilsDJ1990** [comment]
@radek8 got some errors for language and icons , which would be the current ones ? So many different places with files im getting confused alot

**Comment by radek8** [comment]
Which icon set do you prefer?

**Comment by DevilsDJ1990** [comment]
@radek8 Do I download this one ? [https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware)  and use the language , config , TFT35 folder from there and your bin file ?

**Comment by radek8** [comment]
the language pack is here

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update/Language%20Packs

the config.ini is here

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update

folder with icons
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update/THEME_The%20Round%20Miracle%20Menu%20Material%20theme

bin file I sent

**Comment by DevilsDJ1990** [comment]
@radek8 DUDE I LOVE YOU , it worked , FINALLY IT WORKED . no more No Printer Attached.
But just so I know for the future - so this means my TFT original pins are faulty and also did you modify something like this somewhere - not sure what it is and where and how just saw it in another post 
/* 
* SERIAL_PORT: communicating with host(Marlin, smoothieware, etc...)
 * SERIAL_PORT_X: communicating with other controller(Octoprint, ESP3D, other UART Touch Screen, etc...)
 */
#define SERIAL_PORT   _USART3  //default usart port
#define SERIAL_PORT_2 _USART1
#define SERIAL_PORT_3 _USART2
#define SERIAL_PORT_4 _UART4

**Comment by radek8** [comment]
Looks like you have faulty pins on the SR232 connector.
for you, this means that you cannot use a precompiled BIN file and you have to compile your own after editing.
Editing is easy.
The red line is the original, the green one replaces it

![image](https://user-images.githubusercontent.com/46979052/110254270-cdd05c00-7f8e-11eb-8c1e-1615652254d7.png)

**Comment by radek8** [comment]
If you use an additional module of the 5V power supply, then you have the wrong jupmer installed.

![image](https://user-images.githubusercontent.com/46979052/110254725-9b276300-7f90-11eb-80b1-f300dc61607c.png)

**Comment by DevilsDJ1990** [comment]
Yeah havent reached that far yet , I will be adding lights , 3D Touch sensor , might add the UPS module and the automatic power shutdown module . This is what I have so far , I have a 1000W laser at work and I work with stainless steell , I decided I wanted as little plastic parts as possible , so everything except the hotend mounts for fans is metal so far , modeled and tested by me. Including the bed support frame. Size for now is X310 , Y310 , Z650
![IMG_20210304_190622](https://user-images.githubusercontent.com/80215885/110255969-0d06a900-7f9f-11eb-9366-7748cdea59c9.jpg)
![IMG_20210304_190531](https://user-images.githubusercontent.com/80215885/110255971-0e37d600-7f9f-11eb-926d-301ed6914c02.jpg)
![IMG_20210304_190542](https://user-images.githubusercontent.com/80215885/110255972-0ed06c80-7f9f-11eb-920c-5c9638549e68.jpg)
![IMG_20210304_190547](https://user-images.githubusercontent.com/80215885/110255973-0f690300-7f9f-11eb-9008-8635a361c9de.jpg)
![IMG_20210304_190552](https://user-images.githubusercontent.com/80215885/110255975-10019980-7f9f-11eb-89ce-b6a3d1a7be94.jpg)
![IMG_20210304_190559](https://user-images.githubusercontent.com/80215885/110255976-109a3000-7f9f-11eb-970e-8d6a225fa068.jpg)
![IMG_20210304_190615](https://user-images.githubusercontent.com/80215885/110255977-1132c680-7f9f-11eb-897f-ead242266986.jpg)

**Comment by radek8** [comment]
The X-axis belt tensioner is not good :-)
https://www.aliexpress.com/item/4000253369657.html?spm=a2g0o.productlist.0.0.533169604cxoC5&algo_pvid=6c61d042-0b15-4cac-a63e-369887e2b7f0&algo_expid=6c61d042-0b15-4cac-a63e-369887e2b7f0-2&btsid=2100bdcf16151568879834962eabef&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by DevilsDJ1990** [comment]
I have actually ordered those , they are arriving tommorow [https://www.aliexpress.com/item/4000127067311.html?spm=a2g0s.9042311.0.0.51194c4dfePSvD](https://www.aliexpress.com/item/4000127067311.html?spm=a2g0s.9042311.0.0.51194c4dfePSvD)   , there is alot more to be done - I have to decide on how to reinforce the Z axis , something like they did on the CR10 , I have to decide where the electronics will be ( either under the bed - display in front or to make a separate enclosure for the electronics ) , I have to make mounts for cable chains for the cables for the bed and Z axis , decide on what extruder to use ( I have tryed BMG and Titan clones on other printers I own) and probably more that I cant think of now. IF you are interested I can keep you up to date somewhere and I am open to suggestions and opinions. When everything is up and working I will probably post files for the parts I made somewhere , dxf files for the metal version and stl for printed plastic ones ( since I started with test ones before making the metal version).
I was thinking maybe getting one of these [https://www.aliexpress.com/item/1005001398845300.html?spm=a2g0s.8937460.0.0.24fc2e0eaigbfI](https://www.aliexpress.com/item/1005001398845300.html?spm=a2g0s.8937460.0.0.24fc2e0eaigbfI) or making again out of metal a version for the cr10 type hotend maybe one of these for extruder but not sure if they are good [https://www.aliexpress.com/item/4000648526348.html?spm=a2g0s.8937460.0.0.1f212e0e6p9AdE](https://www.aliexpress.com/item/4000648526348.html?spm=a2g0s.8937460.0.0.1f212e0e6p9AdE) , also as I said about electronics maybe I will make them like the WANHAO

**Comment by DevilsDJ1990** [comment]
@radek8 Is it here that I need to do this ? And then just compile using the newest files ?
![Untitled2](https://user-images.githubusercontent.com/80215885/110341477-0a559380-8033-11eb-93b7-fd30626cbb73.jpg)

**Comment by radek8** [comment]
Yes

**Comment by whiney1** [comment]
> 
> 
> It looks like a faulty serial port pin on the SKR or TFT connector.
> Want to try another port?
> It has happened several times that the RS232 connector on the TFT was defective
> 
> To test, disconnect the RX and TX pin of the SR232 cable to the TFT and connect them to the RX and TX pins on the UART3 connector.
> To do this, you need to upload the modified FW to the TFT
> [BIGTREE_TFT35_V3.0.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/6093274/BIGTREE_TFT35_V3.0.26.x.zip)

You absolute legend radek8, that fixed it right up. I modified the pin file and moved the cables - the back of my TFT looks a little different than the picture that was put up in this thread but I made sure to use the Tx3/Rx3 pins.

I'm Devilsdj1990 asked you the follow up questions on how to modify the files/cables though because I would have had to do that too :D

Thanks!

**Comment by Korpz58** [comment]
I apologize for this, but I am so new to this stuff I make a first grader look like a College graduate. Not sure if this is where I can post but I'm going to try. I also bought a ender 3, read all the things on the skr mini e3 v3, and the tft 35. Was able to put all the stuff in and now get the "no printer attached". Even before that I only managed to print 1 straight line. No idea how to flash firmware (although read up on it and does nothing at all. I'm ready to throw this thing through the window and it's a shame as I can do nothing at all with this. Any help would be greatly appreciated, and I truly mean that.
Thank you
