### ISSUE TITLE
SKR Display V3 Found outdated data: Icons: Update Required

### ISSUE THREAD

**Issue by XeroDay99** [bigtreetech/BIGTREETECH-TFT35-V3.0#122]
SKR Display V3 

Found outdated data:

Icons: Update Required

**Comment by radek8** [comment]
So update the icons.
What is the problem?
čti manuál...
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

**Comment by radek8** [comment]
please close this ticket

**Comment by XeroDay99** [comment]
Great answer! So professional. Now I wonder people just return the product!

**Comment by radek8** [comment]
What is unprofessional about my answers?

The error message was clear and there was no reason to write an error message.
Or am I wrong?

**Comment by radek8** [comment]
I'm a 3D printer user just like you.
I try to help others.
People write requests for help here and then don't even answer their own ticket.
The fact that they should lock him up when they don't need him doesn't occur to them.
Thank you for your answer even though it was a bit sarcastic, and for closing the ticket.

PS:
It's a great product, it would be a shame to return it :-D
