### ISSUE TITLE
Custom Firmware Binary and config.ini

### ISSUE THREAD

**Issue by jerryfudd** [bigtreetech/BIGTREETECH-TFT35-V3.0#124]
Hi,

Just got the TFT35 E3 V3.0 and since I've been customising my Marlin firmware for my SKR Mini 1.2 was loving the fact I can do the same for the TFT35.

I've generated my BIGTREE_TFT35_V3.0_E3.26.x.bin and placed on the SD card along with the contents of the TFT35 with whatever menu system I want.

However, what I don't get is that on boot up the sd card firmware contents don't get applied to the screen. That is unless I include the config.ini file - which then appears to override most of my BIGTREE_TFT35_V3.0_E3.26.x.bin file.

Can the BIGTREE_TFT35_V3.0_E3.26.x.bin be applied without config.ini as at the moment it seems an annoyance that I have to set my preferences in two places - or am I doing something wrong?

**Comment by jerryfudd** [comment]
issue was that I wasn't reseting to default settings after applying the .bin which now appears to be working as a solo file on the card.

**Comment by oldman4U** [comment]
Put the precompiled firmware, the TFT folder of your screen and the edited config.ini on the SD card and all will be fine. Like described in the Readme of the firmware repository.

**Comment by jerryfudd** [comment]
> Put the precompiled firmware, the TFT folder of your screen and the edited config.ini on the SD card and all will be fine. Like described in the Readme of the firmware repository.

all sorted, as per my reply.

after applying the custom firmware I had to reset to default settings.

no idea why at first i needed the .ini but works fine with just the .bin now.

**Comment by oldman4U** [comment]
Perfect. There is no need to edit configuration.h or compile firmware is
what I wanted to add. Otherwise other users believe they have to what you
wrote.

Please help the community and close the ticket once you do not need it
anymore. Thank you

jerryfudd ***@***.***> schrieb am Fr. 26. März 2021 um 06:46:
