### ISSUE TITLE
Problems with "No printer attached"

### ISSUE THREAD

**Issue by freytod** [bigtreetech/BIGTREETECH-TFT35-V3.0#129]
Hi,
i just got my TFT35-E3-V3.0 and a SKR mini E3 V2. I want to use both on an Ender 5 (default/early 2019) with BLTouch.
The board works fine but the screen doesn't seem to find the board. 
I can use the marlin-mode without any problems but the touchscreen-mode wont work, no matter what I have tried.

Things I tried:
-changed the baudrate on TFT and marlin/configuration.h between 115200 and 250000
-changed SERIAL_PORT and SERIAL_PORT_2 between -1 and 2 in every possible configuration
-used my own compile of Marlin 2.0.9 as well as BTTs precompiled version for Ender5
-searched in other threads and found a [file](https://www.dropbox.com/s/k7tb4sck5d2h5bb/BTT%20TFT%20to%20BTT%20Mainboards%202021.pdf?dl=0) where the serial_ports settings are mentioned
-tested the serialcable and also replaced it with wires
-tried to use UART3 instead of the serialport like mentioned [here](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/issues/120#issuecomment-791666846) and used a custom compiled version of the FW with changes mentioned [here](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/issues/120#issuecomment-792350134) (pictures below)
![IMG_20210623_214355](https://user-images.githubusercontent.com/63155473/123160995-26106880-d46f-11eb-8f11-ba2a5733ed28.jpg)
![IMG_20210623_214413](https://user-images.githubusercontent.com/63155473/123161000-27419580-d46f-11eb-8e08-1baabf4b1d1d.jpg)
![IMG_20210623_214430](https://user-images.githubusercontent.com/63155473/123161003-27da2c00-d46f-11eb-9fb8-a73387ab8422.jpg)

I have no Idea what to try anymore and my best guess is, that my TFT is just broken. 
Maybe someone can help me if possible.

Thanks and best regards

[Configuration.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/6704623/Configuration.zip)
[config.ini.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/6705119/config.ini.zip)

**Comment by radek8** [comment]
According to the photo, you have a rotated connector

**Comment by freytod** [comment]
So I just have to switch the pins of the original cable on the SKR mini?

**Comment by radek8** [comment]
A brown cable goes to the RESET pin on the SKR.
A blue cable goes to the RESET pin on the TFT.

**Comment by radek8** [comment]
The connector is rotated 180 °

**Comment by radek8** [comment]
Sorry my mistake, it's fine

**Comment by radek8** [comment]
The right setting is for you    SERIAL_PORT 2

**Comment by freytod** [comment]
> 
> 
> The right setting is for you SERIAL_PORT 2

I have SERIAL_PORT 2 in my configuration.h but it still doesnt want to work
But thanks for your help! I appreciate it.

**Comment by radek8** [comment]
Do you have the same serial port speed on both?
115200

**Comment by freytod** [comment]
> 
> 
> Do you have the same serial port speed on both?
> 115200

Yes, my latest configuration.h is attached to the initial post if that helps...

**Comment by radek8** [comment]
There is no ini file for TFT.
So I don't know what the speed is on TFT

**Comment by radek8** [comment]
Try commenting on a line in Marlim
#define BAUDRATE_2 115200 // Enable to override BAUDRATE
This is a new feature, there could be a problem.

**Comment by freytod** [comment]
> 
> 
> There is no ini file for TFT.
> So I don't know what the speed is on TFT

You are right, my bad. Attached the ini.


> 
> 
> Try commenting on a line in Marlim
> #define BAUDRATE_2 115200 // Enable to override BAUDRATE
> This is a new feature, there could be a problem.

Tried it with and without #define BAUDRATE_2 115200
Doesn't make a difference

**Comment by radek8** [comment]
If you connect the printer via USB to a PC and send the M503 S0 command from the PC from Pronterface
Will TFT respond?

**Comment by freytod** [comment]
> 
> 
> If you connect the printer via USB to a PC and send the M503 S0 command from the PC from Pronterface
> Will TFT respond?

No, nothing happens if I do that:

SENDING:M503 S0
  G21    ; Units in mm (mm)
  M149 C ; Units in Celsius
  M200 S0 D1.75
  M92 X80.00 Y80.00 Z400.00 E93.00
  M203 X500.00 Y500.00 Z5.00 E25.00
  M201 X500.00 Y500.00 Z100.00 E5000.00
  M204 P500.00 R500.00 T500.00
  M205 B20000.00 S0.00 T0.00 J0.08
  M206 X0.00 Y0.00 Z0.00
  M420 S0 Z10.00
  M145 S0 H200.00 B60.00 F255
  M145 S1 H235.00 B80.00 F255
  M301 P21.73 I1.54 D76.55
  M304 P50.71 I9.88 D173.43
  M710 S255 I0 A1 D60 ; (100% 0%)
  M851 X-40.00 Y-15.00 Z0.00
  M906 X580 Y580 Z580
  M906 T0 E650
  M569 S1 X Y Z
  M569 S1 T0 E
  M900 K0.00
  M603 L350.00 U550.00

**Comment by radek8** [comment]
If you have correctly tested the standard serial port on the TFT and also UART3 and both e behave the same, it is unlikely that both will be defective. Then there would be a problem with the SKR serial connector

**Comment by freytod** [comment]
I hope I have correctly tested everything with the standard port and the UART3... Wasn't sure if the changes I made to the TFT FW are in pin_tft_35_v3_0.h and not in pin_tft_35_e3_v3_0.h.
Is there a difference? pin_tft_35_e3_v3_0.h is nearly empty

**Comment by radek8** [comment]
It happened several times that the serial connection cable was defective. Can you try another cable between TFT and SKR?

To your question? TFT 35 V3 and TFT 35 E3 V3 both use the same set of pins pin_tft_35_v3_0.h
TFT 35 E3 V3 also the file pin_tft_35_e3_v3_0.h
In both cases, you are editing the same file.

**Comment by radek8** [comment]
Do you have the option to try another TFT, or connect your TFT to another printer (another Marlin motherboard)?

**Comment by freytod** [comment]
> 
> 
> It happened several times that the serial connection cable was defective. Can you try another cable between TFT and SKR?

I tried to connect the TFT by using the singlecable connections in the serialport with the FW provided by BTT. Doesnt change anything..



> 
> 
> Do you have the option to try another TFT, or connect your TFT to another printer (another Marlin motherboard)?

The only other TFT i have is the originial 12864 and the only other motherboard is the Creality V1.1.2. Not sure if this helps since connection via EXP3 works just fine.

**Comment by radek8** [comment]
Neither the original display nor the original Ender board can be used to test functionality.

The SKR could theoretically test the connection to serial port 1 to rule out the possibility that there is a faulty pin on the SKR connector, similar to what you did with remapping ports to TFT.

I don't have a SKR mini E3 to try it out, but according to the wiring diagram it should work.

**Comment by freytod** [comment]
> 
> 
> The SKR could theoretically test the connection to serial port 1 to rule out the possibility that there is a faulty pin on the SKR connector, similar to what you did with remapping ports to TFT.

How can I test the connection? I'm not very experienced in those things tbh..

**Comment by radek8** [comment]
I'm at work now and I don't have time. In the evening, I could look at and write how and where to get involved, and how to edit Marlin.

**Comment by freytod** [comment]
> 
> 
> I'm at work now and I don't have time. In the evening, I could look at and write how and where to get involved, and how to edit Marlin.

That would be a great help, thank you!

**Comment by freytod** [comment]
I looked at the pin-diagramms a little bit. Maybe I'm wrong but shouldn't Tx on the SKR go to Rx on the TFT and vice versa? If I connect the serialcable, it would connect Tx to Tx and Rx to Rx... Will try to connect them manually.

Edit: Okay, it does not make a difference, still wont work.

**Comment by radek8** [comment]
You can try both variants

**Comment by radek8** [comment]
Upload the original FW to the TFT. Connect the serial connector to the RS232 socket.
Set the port speed to 115200.
Disconnect the 10Pin cable between the SKR and the TFT.
Connect the serial cable. but without the RX and TX pin on the SKR
Connect the RX and TX contacts to pins RX1 and TX1 in the EXP connector.


![image](https://user-images.githubusercontent.com/46979052/123320957-b5cb1b00-d532-11eb-8914-b5a77a34fb7f.png)



Set in Marlin
#define SERIAL_PORT 1
#define BAUDRATE 115200

In the file
pins_BTT_SKR_MINI_E3_common.h
comment lines 146 and 147
// # define BTN_EN1 PA9
// # define BTN_EN2 PA10

Compile Marlin.

**Comment by radek8** [comment]
Do you have these options enabled (uncommented)?

#define M115_GEOMETRY_REPORT
#define M114_DETAIL

**Comment by freytod** [comment]
> 
> 
> Do you have these options enabled (uncommented)?
> 
> #define M115_GEOMETRY_REPORT
> #define M114_DETAIL

No, shall I?

If I do, what you suggested in the post above, the display stays black...

**Comment by radek8** [comment]
> > Do you have these options enabled (uncommented)?
> > #define M115_GEOMETRY_REPORT
> > #define M114_DETAIL
> 
> No, shall I?


Yes you must !!!

**Comment by radek8** [comment]
> 
> If I do, what you suggested in the post above, the display stays black...

Do you have switched to touch mode ?!

**Comment by freytod** [comment]
> 
> 
> > If I do, what you suggested in the post above, the display stays black...
> 
> Do you have switched to touch mode ?!

yes, touchmode is on default

**Comment by radek8** [comment]
Touch mode must boot even if the serial port does not work.

**Comment by radek8** [comment]
When is the display black?

**Comment by freytod** [comment]
The  serialport doesnt seem to give power anymore. It has yesterday without doubt. Tried it again with a normal fw on the SKR. Still black. If I connect SKR-EXP1/EXP3-TFT, the TFT works.

**Comment by radek8** [comment]
send connection photo

**Comment by radek8** [comment]
It must only work with a serial 5 pin connector

**Comment by freytod** [comment]
> 
> 
> It must only work with a serial 5 pin connector

It doesn't. I tried somethings and by using the 5V power of the EXP1 on the SKR, it seems to work again. 
![IMG_20210624_221703](https://user-images.githubusercontent.com/63155473/123326882-0db95000-d53a-11eb-8d39-2c1e5f6219b8.jpg)
![IMG_20210624_221647](https://user-images.githubusercontent.com/63155473/123326890-0eea7d00-d53a-11eb-9ba2-05b34fc0e315.jpg)

connected it like you suggested with the firmware changes you suggested. Still "no printer attached"
I'm feeling a bit dumb right now since I c an't figure out the problem...

**Comment by freytod** [comment]
Okay, I changed red/orange and I got "failed to enable bed leveling" but the printer seems to be attached now. It shows at least the temperatures.

**Comment by radek8** [comment]
This means that the display is OK and the problem is with the SKR on the TFT connector

**Comment by freytod** [comment]
> 
> 
> This means that the display is OK and the problem is with the SKR on the TFT connector

Yes, I think so, too. I will try to exchange the board. Sadly it was a bundle, so I may get a good SKR but a bad TFT in the next package... Hopefully they accept the exchange of just one product. 

Thanks a lot for your help! Wouldn't have gotten that far without you.

**Comment by radek8** [comment]
If they do not accept the complaint, it can be used in an emergency. Only the connection of the encoder would be solved.

**Comment by radek8** [comment]
One more question.
Did you enable M115 and M114 only now, or did you try the original connection with the M115 and M114 option enabled?
Disabled M114 and M115 may cause a printer not connected message.

**Comment by freytod** [comment]
> 
> 
> One more question.
> Did you enable M115 and M114 only now, or did you try the original connection with the M115 and M114 option enabled?
> Disabled M114 and M115 may cause a printer not connected message.

Just tried it now with the last build of my fw for the SKR. 
I will try again with the normal connection and respond.

**Comment by radek8** [comment]
Don't forget to change too
#define SERIAL_PORT 2

**Comment by freytod** [comment]
> 
> 
> Don't forget to change too
> #define SERIAL_PORT 2

Did it in two different folders anyways. But I still got the problem of no power over serial. I can just power it with EXP. And than, the TFT still doesn't work. So the serialport of the SKR is broken.

**Comment by radek8** [comment]
Do you have the red jumper in the correct position?

**Comment by freytod** [comment]
> 
> 
> Do you have the red jumper in the correct position?

Which red jumper are you talking about?

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/123330872-e0bb6c00-d53e-11eb-9fef-25ec7e3d90ac.png)

**Comment by freytod** [comment]
Isn't that one for neo pixel?

**Comment by radek8** [comment]
I don't know how it is with SKRminiE3, but with SKRV1.4 it switches the power supply of the probe neopixel and TFT between the integrated 5V source and the additional 5V module (which you don't have). In the wrong position, the TFT connector would not be powered.

**Comment by freytod** [comment]
Seems to be the correct way. It powers TFT and BLTouch if I activate the onboard 5V. My BLTouch has power.

**Comment by radek8** [comment]
So what is the conclusion?
Faulty pins on the SKR in the TFT connector?

**Comment by freytod** [comment]
My conclusion is faulty pins on the SKR. That i get no power over the serialport is just one thing. I will try to exchange the SKR alone. 
Thanks again for your help and your time.

**Comment by radek8** [comment]
Have a nice day

**Comment by freytod** [comment]
Thanks, you too.
I will leave this issue open until I get the new board.

**Comment by radek8** [comment]
Hello
It's possible that your SKR board was OK.
The problem could be in Marin.
It is said that it does not communicate on serial port 0
see:
https://github.com/MarlinFirmware/Marlin/issues/22283
https://github.com/MarlinFirmware/Marlin/pull/22284

**Comment by freytod** [comment]
> Hello
> It's possible that your SKR board was OK.
> The problem could be in Marin.
> It is said that it does not communicate on serial port 0
> see:
> [MarlinFirmware/Marlin#22283](https://github.com/MarlinFirmware/Marlin/issues/22283)
> [MarlinFirmware/Marlin#22284](https://github.com/MarlinFirmware/Marlin/pull/22284)

Thank you for that! But I measured the voltage of the serial port and it was 0. I also tested if there was a connection between the 5V-rail (the red jumper) and the 5V pin. Also nothing. The connector is faulty anyways and I will receive a new one. Took me nearly a week of sending proofs to the seller... :D

**Comment by radek8** [comment]
OK
The problem is said to be at speeds of 250000 and higher, you tested at 115200.

**Comment by freytod** [comment]
Got my new SKR yesterday.
Just installed the Firmware and everything worked out fine without issues. The only thing I have left is that my TFT shows "failed to enable bed leveling" on startup. I guess I just have to disable it since the BLTouch works as a Z-probe. 
Thank you for your help, I will close this thread soon.

**Comment by radek8** [comment]
If you no longer have a problem, can you close the ticket?

**Comment by freytod** [comment]
Sure, I just forgot about it...
