### ISSUE TITLE
TFT35 V3 custom menu items

### ISSUE THREAD

**Issue by brasco901** [bigtreetech/BIGTREETECH-TFT35-V3.0#13]
Is there a way to add additional pages/menu items to the touchscreen?

**Comment by brasco901** [comment]
Anyone?

**Comment by coreflake1** [comment]
[](https://github.com/bigtreetech/BIGTREETECH-TFT35-V1.2/blob/master/TFT%2035%20screen%20customize.pdf)

Please let me know if you make something :). 
I think the graphics on the screen are horrible.

**Comment by extesy** [comment]
@coreflake1 This guide only explains how to replace _existing_ icons, there is no information about adding new items or pages.

**Comment by GenaUser** [comment]
I need this possibility too.
Currently, I am forced to use MKS screens because of this.

**Comment by thisiskeithb** [comment]
> Please let me know if you make something :).

Check out these icons: [tft35-v3-0-iconpack](https://theveel.com/sdm_downloads/tft35-v3-0-iconpack/)

> This guide only explains how to replace existing icons, there is no information about adding new items or pages.

You'll have to take a look a the existing code. There's no drag & drop/easy way to add new buttons or screens.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
