### ISSUE TITLE
ESP01s stopped working after upgrade firmware

### ISSUE THREAD

**Issue by belkevglaz** [bigtreetech/BIGTREETECH-TFT35-V3.0#130]
I have esp01s connected to tft35 diplay. All working well before. 
After upgrade to the last commit c7842cf8f7d4bfe0395cbaba4ed538ce005af581 esp module not working  (no wifi conenctions and led blinking on the board )
How to fix it ? Need to do some configurations in firmware ? 
Thanks

**Comment by oldman4U** [comment]
You should ask this in the firmware repository.

With the latest firmware version, all serial ports except the one which connects with the mainboard are disabled by default but can be turned on by editing the related part of the config.ini.

**Comment by belkevglaz** [comment]
Could you point me please in config.ini where it is ?

**Comment by belkevglaz** [comment]
You are talking about `multi_serial:0` ? My esp connected to EXP1 port, what I need to enable, `multi-serial:1` ? 
Anyway, thanks for the tip.

**Comment by belkevglaz** [comment]
Updated firmware with `multi_serial:7` ( all serial ports are enabled) does not help. esp still not work.

**Comment by oldman4U** [comment]
Restart after firmware update. 

You have it connected to the dedicated WIFI connector.![image](https://user-images.githubusercontent.com/54359396/123535659-7dd7f980-d725-11eb-943a-c5741379b28a.jpeg)

**Comment by belkevglaz** [comment]
Fixed. Problem was in pins contact. Re-installed esp and it started to work.
