### ISSUE TITLE
Problem with ABL level corners

### ISSUE THREAD

**Issue by bubulgum** [bigtreetech/BIGTREETECH-TFT35-V3.0#132]
hi, all.
I'm using Mega zero 2 with SKR mini E3 v2 and TFT35 E3.
Firmware KAD_marlin_2.0.9.
If i'm trying to use ABL and push "Start:" to level corners, printer only level Left corners and don't move to Right part.
If i push buttons Left front corner or Left bottom corner, printer Level them, but no reaction for buttons Right front and Right bottom. Looks like they are not active.
I can't figure aout where is problem, in marlin or in TFT firmware.
If echo M111, as i understand terminal send G30 E1 X194 Y194 and G30 E1 X41 Y194 to that points, but in fact don't move BL to that points...please find photo in attached (sorry, i'm new and don't know how to debug by text).
[G30 E1 X41 Y41](https://prnt.sc/19ngoaq)
[G30 E1 X194 Y41](https://prnt.sc/19ngrhn)
[G30 E1 X194 Y194](https://prnt.sc/19ngu8b)
[G30 E1 X41 Y194](https://prnt.sc/19ngwsm)
So I can only Level 2 corners, [photo](https://prnt.sc/19nharm)
If use ABL with mesh, all mesh levels, but right side not so well, i think because can't level corners.

**Comment by bubulgum** [comment]
> hi, all.
> I'm using Mega zero 2 with SKR mini E3 v2 and TFT35 E3.
> Firmware KAD_marlin_2.0.9.
> If i'm trying to use ABL and push "Start:" to level corners, printer only level Left corners and don't move to Right part.
> If i push buttons Left front corner or Left bottom corner, printer Level them, but no reaction for buttons Right front and Right bottom. Looks like they are not active.
> I can't figure aout where is problem, in marlin or in TFT firmware.
> If echo M111, as i understand terminal send G30 E1 X194 Y194 and G30 E1 X41 Y194 to that points, but in fact don't move BL to that points...please find photo in attached (sorry, i'm new and don't know how to debug by text).
> [G30 E1 X41 Y41](https://prnt.sc/19ngoaq)
> [G30 E1 X194 Y41](https://prnt.sc/19ngrhn)
> [G30 E1 X194 Y194](https://prnt.sc/19ngu8b)
> [G30 E1 X41 Y194](https://prnt.sc/19ngwsm)
> So I can only Level 2 corners, [photo](https://prnt.sc/19nharm)
> If use ABL with mesh, all mesh levels, but right side not so well, i think because can't level corners.

same issue with KAD_marlin_2.0.9.1
and BIGTREE_TFT35_V3.0_E3.27.x.bin with config.ini from 08 Jul 2021

**Comment by radek8** [comment]
Send Marlin and tft configuration files

**Comment by bubulgum** [comment]
> Send Marlin and tft configuration files

[Marlin.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/6794641/Marlin.zip)
[TFT.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/6794642/TFT.zip)

**Comment by radek8** [comment]
Depending on your configuration, the points at position X194 are not available for the probe.
The problem is in your bed configuration and probe point position.

**Comment by radek8** [comment]
The position of the probe on the X axis is 38 mm to the left of the nozzle.
The size of the bed is 220.
You have MAX_SOFTWARE_ENDSTOPS enabled for the X and Y axes.
Max position equals BED_SIZE.
Therefore, the nozzle cannot move beyond the bed

If the probe should move to position X 194
the nozzle would be at position 194 + 38 = 232
So the nozzle would go out of bed and you're forbidden.
 
In touch mode you have defined
level_edge_distance: 20
220-20 + 38 = 238
So the nozzle would go out of bed. But MAX_SOFTWARE_ENDSTOPS will not allow this

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/125175601-a3590e80-e1cd-11eb-8fb5-b316bfc790d5.png)

![image](https://user-images.githubusercontent.com/46979052/125175613-b7047500-e1cd-11eb-92c0-b58933598763.png)

![image](https://user-images.githubusercontent.com/46979052/125175647-cd123580-e1cd-11eb-9cf1-30bea7f3d164.png)

**Comment by bubulgum** [comment]
> The position of the probe on the X axis is 38 mm to the left of the nozzle.
> The size of the bed is 220.
> You have MAX_SOFTWARE_ENDSTOPS enabled for the X and Y axes.
> Max position equals BED_SIZE.
> Therefore, the nozzle cannot move beyond the bed
> 
> If the probe should move to position X 194
> the nozzle would be at position 194 + 38 = 232
> So the nozzle would go out of bed and you're forbidden.
> 
> In touch mode you have defined
> level_edge_distance: 20
> 220-20 + 38 = 238
> So the nozzle would go out of bed. But MAX_SOFTWARE_ENDSTOPS will not allow this


i have commened MAX_SOFTWARE_ENDSTOPS, but nozzle still don't move to right side.
![image](https://user-images.githubusercontent.com/21036145/125196773-9f8cc100-e28d-11eb-8613-998346326d9f.png)

**Comment by bubulgum** [comment]
> > The position of the probe on the X axis is 38 mm to the left of the nozzle.
> > The size of the bed is 220.
> > You have MAX_SOFTWARE_ENDSTOPS enabled for the X and Y axes.
> > Max position equals BED_SIZE.
> > Therefore, the nozzle cannot move beyond the bed
> > If the probe should move to position X 194
> > the nozzle would be at position 194 + 38 = 232
> > So the nozzle would go out of bed and you're forbidden.
> > In touch mode you have defined
> > level_edge_distance: 20
> > 220-20 + 38 = 238
> > So the nozzle would go out of bed. But MAX_SOFTWARE_ENDSTOPS will not allow this
> 
> i have commened MAX_SOFTWARE_ENDSTOPS, but nozzle still don't move to right side.
> ![image](https://user-images.githubusercontent.com/21036145/125196773-9f8cc100-e28d-11eb-8613-998346326d9f.png)

**Comment by radek8** [comment]
MAX_SOFTWARE_ENDSTOPS Don't off. It's printer protection.  Edit the coordinates of leveling points. 
Have you also initialized EEPROM?

**Comment by radek8** [comment]
Send a photo of the printer with the leveling probe

**Comment by bubulgum** [comment]
For what does use for button "Distance" on the screen?
Min 41 and MAX 100, i have change to 50 and it works.

**Comment by radek8** [comment]
It is the distance of the measuring point from the edge of the bed
 
level_edge_distance: 50
220-50 + 38 = 208
208<220  Yes, this will work

**Comment by bubulgum** [comment]
> It is the distance of the measuring point from the edge of the bed
> 
> level_edge_distance: 50
> 220-50 + 38 = 208
> 208<220 Yes, this will work

i'm confused of the formula. 
Because before was 41.
And actually in my situation NOZZLE_TO_PROB_OFFSET = 40, and BED_SIZE = 225
So 220-41 + 40 = 219...but thats not works.
I have tried 42, 43...49 and only 50+ works.

**Comment by bubulgum** [comment]
and one more thing, after setup all corners i have saved to EEPROM, but after i turn off and turn on printer, settings come back to 0.
For the MESH still ok.

**Comment by radek8** [comment]
Yes, if you have a probe offset of 40 on the X axis, then 41 should work.
Can you enter the answer to the commands here?
M503
and
M115
Thank you

**Comment by bubulgum** [comment]
Sorry, how to log into TXT file? 
if i enable M928 log.txt there is empty file LOG.txt

**Comment by radek8** [comment]
Connect the printer to the computer and use Pronterface

**Comment by bubulgum** [comment]
> Connect the printer to the computer and use Pronterface

Thank you

I have reset firmware and have not done ABL and Corner LVLs

Connecting...
Printer is now online.
 M503
SENDING:M503
echo:  G21    ; Units in mm (mm)
echo:  M149 C ; Units in Celsius
echo:; Steps per unit:
echo: M92 X80.00 Y80.00 Z400.00 E385.00
echo:; Maximum feedrates (units/s):
echo:  M203 X500.00 Y500.00 Z5.00 E25.00
echo:; Maximum Acceleration (units/s2):
echo:  M201 X500.00 Y500.00 Z100.00 E5000.00
echo:; Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
echo:  M204 P500.00 R500.00 T500.00
echo:; Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>
echo:  M205 B20000.00 S0.00 T0.00 J0.08
echo:; Home offset:
echo:  M206 X0.00 Y0.00 Z0.00
echo:; Auto Bed Leveling:
echo:  M420 S1 Z10.00
echo:  G29 W I0 J0 Z2.18250
echo:  G29 W I1 J0 Z1.43500
echo:  G29 W I2 J0 Z0.82500
echo:  G29 W I3 J0 Z0.18750
echo:  G29 W I4 J0 Z-0.43000
echo:  G29 W I5 J0 Z-1.00000
echo:  G29 W I6 J0 Z-1.69500
echo:  G29 W I0 J1 Z2.16000
echo:  G29 W I1 J1 Z1.47500
echo:  G29 W I2 J1 Z0.80250
echo:  G29 W I3 J1 Z0.14750
echo:  G29 W I4 J1 Z-0.46000
echo:  G29 W I5 J1 Z-1.11000
echo:  G29 W I6 J1 Z-1.71750
echo:  G29 W I0 J2 Z2.26500
echo:  G29 W I1 J2 Z1.63000
echo:  G29 W I2 J2 Z0.94500
echo:  G29 W I3 J2 Z0.29000
echo:  G29 W I4 J2 Z-0.32500
echo:  G29 W I5 J2 Z-0.98500
echo:  G29 W I6 J2 Z-1.58250
echo:  G29 W I0 J3 Z2.36500
echo:  G29 W I1 J3 Z1.66250
echo:  G29 W I2 J3 Z0.96750
echo:  G29 W I3 J3 Z0.29750
echo:  G29 W I4 J3 Z-0.32500
echo:  G29 W I5 J3 Z-0.79500
echo:  G29 W I6 J3 Z-1.57500
echo:  G29 W I0 J4 Z2.39500
echo:  G29 W I1 J4 Z1.75500
echo:  G29 W I2 J4 Z1.08250
echo:  G29 W I3 J4 Z0.40000
echo:  G29 W I4 J4 Z-0.20500
echo:  G29 W I5 J4 Z-0.78750
echo:  G29 W I6 J4 Z-1.48000
echo:  G29 W I0 J5 Z2.53500
echo:  G29 W I1 J5 Z1.85500
echo:  G29 W I2 J5 Z1.19500
echo:  G29 W I3 J5 Z0.48750
echo:  G29 W I4 J5 Z-0.09750
echo:  G29 W I5 J5 Z-0.72750
echo:  G29 W I6 J5 Z-1.33250
echo:  G29 W I0 J6 Z2.58750
echo:  G29 W I1 J6 Z1.92750
echo:  G29 W I2 J6 Z1.42750
echo:  G29 W I3 J6 Z0.14500
echo:  G29 W I4 J6 Z-0.05250
echo:  G29 W I5 J6 Z-0.66500
echo:  G29 W I6 J6 Z-1.28500
echo:; Material heatup parameters:
echo:  M145 S0 H190.00 B60.00 F0
echo:  M145 S1 H230.00 B70.00 F0
echo:; PID settings:
echo:  M301 P17.72 I1.18 D66.76
echo:  M304 P350.00 I63.00 D452.00
; Controller Fan
echo:  M710 S255 I0 A1 D60 ; (100% 0%)
echo:; Power-Loss Recovery:
echo:  M413 S0
echo:; Z-Probe Offset (mm):
echo:  M851 X-40.00 Y-12.00 Z-0.51
echo:; Stepper driver current:
echo:  M906 X800 Y800 Z800
echo:  M906 T0 E800
echo:; Driver stepping mode:
echo:  M569 S1 X Y Z
echo:  M569 S1 T0 E
echo:; Linear Advance:
echo:  M900 K0.00
echo:; Filament load/unload lengths:
echo:  M603 L400.00 U450.00
echo:; Filament runout sensor:
echo:  M412 S0 D7.00

M115
SENDING:M115
FIRMWARE_NAME:Marlin 2.0.9.1-kad1 (Jul 16 2021 01:02:06) SOURCE_CODE_URL:github.com/kad/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Mega Zero 2.0 EXTRUDER_COUNT:1 UUID:dbfccd55-ebba-4615-abd7-196aa438f304
Cap:SERIAL_XON_XOFF:0
Cap:BINARY_FILE_TRANSFER:1
Cap:EEPROM:1
Cap:VOLUMETRIC:0
Cap:AUTOREPORT_POS:1
Cap:AUTOREPORT_TEMP:1
Cap:PROGRESS:0
Cap:PRINT_JOB:1
Cap:AUTOLEVEL:1
Cap:RUNOUT:1
Cap:Z_PROBE:1
Cap:LEVELING_DATA:1
Cap:BUILD_PERCENT:1
Cap:SOFTWARE_POWER:1
Cap:TOGGLE_LIGHTS:0
Cap:CASE_LIGHT_BRIGHTNESS:0
Cap:EMERGENCY_PARSER:1
Cap:HOST_ACTION_COMMANDS:1
Cap:PROMPT_SUPPORT:0
Cap:SDCARD:1
Cap:REPEAT:0
Cap:SD_WRITE:1
Cap:AUTOREPORT_SD_STATUS:0
Cap:LONG_FILENAME:1
Cap:THERMAL_PROTECTION:1
Cap:MOTION_MODES:0
Cap:ARCS:1
Cap:BABYSTEPPING:1
Cap:CHAMBER_TEMPERATURE:0
Cap:COOLER_TEMPERATURE:0
Cap:MEATPACK:0

**Comment by radek8** [comment]
You can uncomment in configuration_adv.h
  #define M115_GEOMETRY_REPORT
and copy the M115 command again?

Another question, do you have a calibrated number of steps per mm?

**Comment by bubulgum** [comment]
> You can uncomment in configuration_adv.h
> #define M115_GEOMETRY_REPORT
> and copy the M115 command again?

Connecting...
Printer is now online.
M115
SENDING:M115
FIRMWARE_NAME:Marlin 2.0.9.1-kad1 (Jul 16 2021 03:23:02) SOURCE_CODE_URL:github.com/kad/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Mega Zero 2.0 EXTRUDER_COUNT:1 UUID:dbfccd55-ebba-4615-abd7-196aa438f304
Cap:SERIAL_XON_XOFF:0
Cap:BINARY_FILE_TRANSFER:1
Cap:EEPROM:1
Cap:VOLUMETRIC:0
Cap:AUTOREPORT_POS:1
Cap:AUTOREPORT_TEMP:1
Cap:PROGRESS:0
Cap:PRINT_JOB:1
Cap:AUTOLEVEL:1
Cap:RUNOUT:1
Cap:Z_PROBE:1
Cap:LEVELING_DATA:1
Cap:BUILD_PERCENT:1
Cap:SOFTWARE_POWER:1
Cap:TOGGLE_LIGHTS:0
Cap:CASE_LIGHT_BRIGHTNESS:0
Cap:EMERGENCY_PARSER:1
Cap:HOST_ACTION_COMMANDS:1
Cap:PROMPT_SUPPORT:0
Cap:SDCARD:1
Cap:REPEAT:0
Cap:SD_WRITE:1
Cap:AUTOREPORT_SD_STATUS:0
Cap:LONG_FILENAME:1
Cap:THERMAL_PROTECTION:1
Cap:MOTION_MODES:0
Cap:ARCS:1
Cap:BABYSTEPPING:1
Cap:CHAMBER_TEMPERATURE:0
Cap:COOLER_TEMPERATURE:0
Cap:MEATPACK:0
area:{full:{min:{x:-7.00,y:-2.00,z:0.00},max:{x:225.00,y:225.00,z:250.00}},work:{min:{x:-7.00,y:-2.00,z:0.00},max:{x:225.00,y:225.00,z:250.00}}}


> Another question, do you have a calibrated number of steps per mm?

I don't know what does it mean and how to do.
I have just upload firmware, because it exactly for my model with my board...
Printer works well...but for now i found only this kind of problems.

**Comment by radek8** [comment]
The configuration looks fine.
home X-axis offset is 0
The probe offset is -40
The work surface is defined on the X axis -7 to 225.
The probe probe should operate at an X-axis coordinate of 184 mm or less.

Step calibration is essential. You can find the procedure on youtube.
Does the physical location of the probe match the parameters in the firmware?

**Comment by bubulgum** [comment]
> Step calibration is essential. You can find the procedure on youtube.

thx, i will



> Does the physical location of the probe match the parameters in the firmware?

yes, this fine and printing fine. 

but i need to setup "Distance" to 50, and every corner i need to up manual by Z, otherwise if move to another corner can scratch bed.

**Comment by radek8** [comment]
Tasdy, you're wrong.
In Marlin you have a defined bed as 225x225,
but you have 235x235 defuncted on the touch screen.
You have to define the same (correct) values everywhere.
fix coubor config.ini on 225.
You also have the wrong size_min value.


![image](https://user-images.githubusercontent.com/46979052/125905499-50630749-2cd2-4ec9-8043-6a77e7f56b3e.png)

![image](https://user-images.githubusercontent.com/46979052/125905686-2a977660-73a2-4559-97cc-4ba58153f723.png)

**Comment by radek8** [comment]
Also bad value
set 41

![image](https://user-images.githubusercontent.com/46979052/125906077-e8b72af7-0c9f-43e9-8576-205004140d11.png)

**Comment by radek8** [comment]
Pokud máte při přesunu mezi sondováním trysku příliš nízkou a hrozí poškrábání, upravte tyto hodnoty.

![image](https://user-images.githubusercontent.com/46979052/125908629-fb48da38-1396-42dd-a45b-d4df4f80ca02.png)



![image](https://user-images.githubusercontent.com/46979052/125908995-a7137e7c-f817-4b97-b240-5e5b0ad03cab.png)

**Comment by bubulgum** [comment]
> Tasdy, you're wrong.
> In Marlin you have a defined bed as 225x225,
> but you have 235x235 defuncted on the touch screen.
> You have to define the same (correct) values everywhere.
> fix coubor config.ini on 225.
> You also have the wrong size_min value.
> 
> ![image](https://user-images.githubusercontent.com/46979052/125905499-50630749-2cd2-4ec9-8043-6a77e7f56b3e.png)
> 
> ![image](https://user-images.githubusercontent.com/46979052/125905686-2a977660-73a2-4559-97cc-4ba58153f723.png)

You are awesome, i missed that part in TFT config.
And i was wrogn about my bed size, you were right 220x220x250.
Now it works perfect!
Thanks a lot!

**Comment by bubulgum** [comment]
> Pokud máte při přesunu mezi sondováním trysku příliš nízkou a hrozí poškrábání, upravte tyto hodnoty.
> 
> ![image](https://user-images.githubusercontent.com/46979052/125908629-fb48da38-1396-42dd-a45b-d4df4f80ca02.png)
> 
> ![image](https://user-images.githubusercontent.com/46979052/125908995-a7137e7c-f817-4b97-b240-5e5b0ad03cab.png)

i have tried to set 10. But this not home.
If i start to L Corner, probe go to each corner without any movement by Z and PROBE only 1 time.
So Probe can set 1 corner, thenwithout Z going to another corner and show "Probe Filed".

**Comment by bubulgum** [comment]
![image](https://user-images.githubusercontent.com/21036145/125928252-f5da04c0-de06-4ecc-82d6-a1143655e9df.png)

i have enabled LEVEL_CORNERS_USE_PROB...but stil nothing.
have tried LEVEL_CORNERS_Z_HOP 10...nothing

![image](https://user-images.githubusercontent.com/21036145/125927952-0cac3822-99c3-4192-ae11-08ff5b167512.png)

**Comment by bubulgum** [comment]
This issue looks like same that i have. But I have tried both and have not fixed this.
https://github.com/pinchies/Marlin/pull/5

**Comment by radek8** [comment]
Somehow I'm getting lost in your problem.
You started leveling in Marlin mode,
then you wanted to deal with corner alignment in touch mode.
You are now setting LEVEL_BED_CORNERS. This is another feature in Marlin mode.

**Comment by radek8** [comment]
Can you send a video what your problem is?

**Comment by radek8** [comment]
If you use the LevelConer function on the touch mode, when you measure the height of the corners of the bed, then after the measurement, the probe should be automatically raised by 10 mm. Unfortunately, an error occurred in the last build.

Try the fix

[BIGTREE_TFT35_V3.0_E3.27.x.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/6833618/BIGTREE_TFT35_V3.0_E3.27.x.zip)

**Comment by bubulgum** [comment]
> If you use the LevelConer function on the touch mode, when you measure the height of the corners of the bed, then after the measurement, the probe should be automatically raised by 10 mm. Unfortunately, an error occurred in the last build.
> 
> Try the fix
> 
> [BIGTREE_TFT35_V3.0_E3.27.x.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/6833618/BIGTREE_TFT35_V3.0_E3.27.x.zip)

Thank you, now works perfectly, except 1 thing.
If turn power off and then power on printer, LevelCorners does not save in EEPROM. Need to Level corners again.
Even after leveled corners manually save to EEPROM.

**Comment by radek8** [comment]
You balance the corners with screws under the bed. This is the function you're using to see the corner. Storing this value in eeprom is meaningless.
