### ISSUE TITLE
BIGTREETECH TFT35 V3.0 mode 12854 background color

### ISSUE THREAD

**Issue by vMeph** [bigtreetech/BIGTREETECH-TFT35-V3.0#15]
was wondering about BIGTREETECH TFT35 V3.0 in mode 12854 all pictures i see the background is black and text green.
is there any options then to change background colors?

**Comment by thisiskeithb** [comment]
Update your TFT firmware to the latest version. It allows you to change the colors in the config or through the TFT interface/on the fly without recompiling now.

**Comment by vMeph** [comment]
@thisiskeithb  that seems to work for the touch mode, but not working for the 12854 mode

```
#define ST7920_BKCOLOR BLACK
#define ST7920_FNCOLOR BLUE
```
works tiuch mode only
the 12854 mode is always black and green

**Comment by thisiskeithb** [comment]
Use the firmware from the [TouchScreenFirmware repo](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware) and not this one. I don't know why BigTreeTech has multiple copies.

**Comment by vMeph** [comment]
i did use that repository......

**Comment by vMeph** [comment]
i have opened a issue on that repository to

**Comment by thisiskeithb** [comment]
In TFT mode, does this work?

> setting -> more set -> Change 12864 background color
> setting -> more set -> Change 12864 font color

Then switch to 12864 mode and test.

**Comment by vMeph** [comment]
doing by the use of the touch you change colors on buttons but wont do nothing
![2](https://user-images.githubusercontent.com/12812111/67618674-3ed40100-f7ea-11e9-8274-36fff1990ada.jpg)
but if you change in config file code then works on touch but on  12864 is always green
![1](https://user-images.githubusercontent.com/12812111/67618679-63c87400-f7ea-11e9-9b0c-b8e47c11d11e.jpg)

**Comment by vMeph** [comment]
the firmware im using is the one you mention
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

**Comment by thisiskeithb** [comment]
Mine doesn't do that, so I don't know.

**Comment by thisiskeithb** [comment]
What does Settings-Info report?

**Comment by vMeph** [comment]
board: bigtreetch_tft35_v3.0
firmware: tft35_v3.0.24.1 oct 21 2019

**Comment by thisiskeithb** [comment]
Strange indeed.

**Comment by vMeph** [comment]
wow it semmed to have worked now
os so before i have edit the conf file ant what i changed was
`#define ST7920_BANNER_TEXT ""` that was to remove the text LCD12864 Simulator
and
```
#define ST7920_BKCOLOR BLACK
#define ST7920_FNCOLOR BLUE
```
so now i just recompile all from scratch and is working.......

**Comment by vMeph** [comment]
now the question is how do i remove the text ``LCD12864 Simulator`` from the lcd qith out recompile the bin file to set
ST7920_BANNER_TEXT "`LCD12864 Simulato"
to
ST7920_BANNER_TEXT ""

**Comment by thisiskeithb** [comment]
> now the question is how do i remove the text LCD12864 Simulator from the lcd with out recompile the bin

You'll have to recompile and set it to `ST7920_BANNER_TEXT ""`. I plan to put in another PR to make that more elegant.

Can you try the attached firmware on your TFT35 to see if the background and font colors change under 12864 mode?
[BIGTREE_TFT35_V3.0.24.1.bin.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/3774775/BIGTREE_TFT35_V3.0.24.1.bin.zip)

**Comment by vMeph** [comment]
yes it worked but resolution is very huge :)

**Comment by vMeph** [comment]
looks more nice with 
`//#define ST7920_FULLSCREEN`
for some reson at fullscreen does look good 
![2](https://user-images.githubusercontent.com/12812111/67619113-68435b80-f7ef-11e9-8e8c-8e1846343b2e.jpg)

if you notice is to stretch the square of fan is not even so looks better with out the fullscreen

**Comment by thisiskeithb** [comment]
> yes it worked but resolution is very huge :)

I like it full-screen mode 🙂 The aspect ratio is not correct in the code, so it's stretched vertically.

> so now i just recompile all from scratch and is working.......

I just saw this. Glad you got your copy working!

**Comment by vMeph** [comment]
ya thanks alot

**Comment by vMeph** [comment]
@thisiskeithb  ya would it be nice to make it bigger but with the correct aspect ratio
about the ST7920_BANNER_TEXT ""will be looking into see your PR, or why not have without text by default, makes no sense to have text anyway, at least from my point of view hehe
thanks alot for your help :)

**Comment by pr0jektcha0s** [comment]
I'm having this same issue with 3.0.25.1. Trying to set colors to Black/Blue. I've enabled and disabled banner text and that made no difference. Any suggestions?

// Marlin Mode Background & Font Color Options
// Current color options from lcd.h: BLACK, BLUE, BROWN, BRRED, CYAN, GBLUE, GRAY, GREEN, MAGENTA, RED, WHITE, YELLOW
#define ST7920_BKCOLOR BLACK
#define ST7920_FNCOLOR BLUE

// Text displayed at the top of the LCD in Marlin Mode.
#define ST7920_BANNER_TEXT ""

// Run Marlin Mode fullscreen. Not recommended for TFT24.
#define ST7920_FULLSCREEN
