### ISSUE TITLE
connection BTTSKR e3 V3 to TFT35 V3.0.1 impossible in Marlin mode

### ISSUE THREAD

**Issue by josgar84** [bigtreetech/BIGTREETECH-TFT35-V3.0#156]
Hello 
i'm trying to connect the SKR e3 V2 to TFT35 V3 and i have some issue. 
The connection RS232 works and i can dysplay the touch screen so when i plug the EXP1's board to EXP3's screen it turns black with a loud beep. I have tried EXP1 and EXP2 and it is the same problem. 
I'm looking for and reading a lot of things for a week and i'm going crazy.
My settings in MArlin are " #define CR10_STOCKDISPLAY" witch is uncommented.

Merci beaucoup.

**Comment by radek8** [comment]
You have to connect the 10-pin cable to the EXP3 connector.

Send a photo of the wiring.
Send Marlin configuration files.

**Comment by josgar84** [comment]
Hello,
as i mentioned above i have tried to connect the stock 10 pins cable to EXP3 and doesn't work at all.
here you are my config files. 

[Configuration.h.txt](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/9793198/Configuration.h.txt)

Thanks a lot

**Comment by josgar84** [comment]
Hello some photos of the wiring
![Board SKRe3miniv2](https://user-images.githubusercontent.com/90221137/196025473-bb35642f-99fd-4893-b34e-c4e15956f4a7.JPG)
![ScreenTFT35E3V2](https://user-images.githubusercontent.com/90221137/196025490-a4ff0721-1ffc-4ecc-86cb-e36491027967.JPG)
Have a nice day
José

**Comment by radek8** [comment]
You misconnected the 10 pin connector.  On one side, turn it 180 degrees.

**Comment by josgar84** [comment]
![IMG_1997](https://user-images.githubusercontent.com/90221137/196041990-bc7ffdfa-3eec-41d1-b251-660fac598abb.JPG)

**Comment by radek8** [comment]
There are several solutions to your problem.
- you can cut the protrusion as you write, or you can
- make a new cable with the correct orientation, or
- turn the opposite piece. (pull off the pins and put on in reverse)

![image](https://user-images.githubusercontent.com/46979052/196042835-fff467c9-b27d-4309-b0d8-680ea25a31d0.png)

**Comment by josgar84** [comment]
Super i am going to try it
thanks

**Comment by josgar84** [comment]
:(   I rotated  the connector (solution 3) as you said but the screen display "Marlin mode" and black screen .
More idea ? 
Merci

**Comment by radek8** [comment]
Marlin's mod should work.
Send your display configuration
config.ini

**Comment by josgar84** [comment]
I haven't got any .the firmware is stock firmware. I'm going to flash a new one and i'll go back tomorrow. I must buy a SD card.
Thank's and have a good evening (or a good day ?).
José

**Comment by radek8** [comment]
In Marlin you have to enable
#define CR10_STOCKDISPLAY

You configure TFT with the Config.ini file.
you must have an active choice
marlin_type:0

**Comment by josgar84** [comment]
IT works ! 
Your are brilliant ! 
Thanks a lot for your help.
José

**Comment by josgar84** [comment]
Sorry i forgot for the others persons who have the same problem i set marlin_type: to 1 into Config.ini file of the screen.
