### ISSUE TITLE
"No printer attached" 

### ISSUE THREAD

**Issue by QUADMAN7** [bigtreetech/BIGTREETECH-TFT35-V3.0#161]
I have a TFT35 connected to a Manta M5P running klipper firmware. I have connected it to the Manta m5p using the EXP1 and EXP2 connectorsseeing as the m5p doesn't have a TFT port. The problem i having is that it says there's no printer attached and I don't know why. Any help would be much appreciated. Thanks.

**Comment by radek8** [comment]
The touch screen in touch mode communicates via the serial port on the TFT connector.
If you have not connected the TFT connector, the display cannot communicate and the printer will not connect.
Display FW is optimized for Marlin, Klipper not all functions will be available.
EXP1 and EXP2 connectors are for Marlin simulated mode communication

**Comment by QUADMAN7** [comment]
I've tried using TFT cable and wiring it up to the main board that way but I still get a "no printer attached error". What should I do to get rid of this error?

**Comment by radek8** [comment]
On the printer you need to define the serial port and speed. The speed must be the same as on TFT.

**Comment by radek8** [comment]
Wrong display choice for Clipper and Manta

**Comment by QUADMAN7** [comment]
Will it not work with klipper and a Manta board even in the marlin simulated mode?

**Comment by radek8** [comment]
I don't know. 
I have no experience with Klipper or Manta board. 
I know Marlin and TFT display.

**Comment by QUADMAN7** [comment]
Thanks anyways!

**Comment by QUADMAN7** [comment]
No solution was found
