### ISSUE TITLE
TFT35 v3.0 with SKR Mini E3 v3 - Stuttering / Pausing / Delay during printing from USB/SD Card (in touch mode)

### ISSUE THREAD

**Issue by makersteve3d** [bigtreetech/BIGTREETECH-TFT35-V3.0#163]
Hello all, I've been searching for a definitive answer to this issue but can't seem to find one.  I've read 'similar' sounding posts (on various sources) which suggest things like buffer count etc, but cannot find a specific thread on here relating to the issue.

The symptoms are, when printing from the TFT35 using either the SD Card or USB whilst in touch mode, the print will momentarily pause mid-print, almost like it's waiting for something to happen or receive further commands - it then resumes anywhere from 0.5 seconds to 1 second later.  The result, depending on where the tool head was at the time leaves blobs, strings or poor overhangs.  This ONLY seems to happen when printing from the TFT USB or SD card in touch mode.  If printing from the on-board SD (on the SKR Mini) via Marlin mode, the issue is not present.

At the moment, I'm having to resort to using the on-board SD running in Marlin mode only, which negates the entire point of having a touchscreen in the first place.

- I'm running the latest TFT35 firmware and the latest Marlin stable release.
- As I'm using the SKR Mini E3, I have the screen connected via TFT Serial and EXP1 connected to EXP3 on the screen.

Thanks for your time,
Steve

**Comment by radek8** [comment]
Are you interested in testing a possible solution to this problem?
If so, write in this thread.
A programmer is looking for someone with this problem to test the fix.

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2761#issuecomment-1557196649

**Comment by makersteve3d** [comment]
> Are you interested in testing a possible solution to this problem? If so, write in this thread. A programmer is looking for someone with this problem to test the fix.
> 
> [bigtreetech/BIGTREETECH-TouchScreenFirmware#2761 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2761#issuecomment-1557196649)

Thank you!  Have done so!
