### ISSUE TITLE
Size of screen info in 2.3 firmware on lcd12864 mode

### ISSUE THREAD

**Issue by brasco901** [bigtreetech/BIGTREETECH-TFT35-V3.0#19]
Is there any way to increase the layout size on the .23 firmware like it is in the .21 firmware?  The information takes up the entire screen in .21,  but in .23 it's a smaller area of the screen when in lcd12864 mode

**Comment by spilz87** [comment]
We have source files, it’s an option to enable or not. You have to compile it with your settings and options

**Comment by brasco901** [comment]
Do you have instructions on how to enable?

**Comment by spilz87** [comment]
Follow the instructions to compile for your board : 
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

The option you want is in BIGTREETECH-TouchScreenFirmware/TFT/src/User/Configuration.h
Uncomment : 
#define ST7920_FULLSCREEN

**Comment by darap89** [comment]
CLOSE THIS ISSUE

**Comment by oldman4U** [comment]
Hello brasco901.

Could you please close this ticket.

Thank you

**Comment by oldman4U** [comment]
Hello brasco901.

Could you please close this ticket.

Thank you

**Comment by oldman4U** [comment]
@bigtreetech Please close this unneeded ticket. Thank you

**Comment by oldman4U** [comment]
@bigtreetech Could you please close this very old ticket unused ticket

This could help new users find tickets which already cover their topic.

Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
