### ISSUE TITLE
[QUESTION] Source files

### ISSUE THREAD

**Issue by Patag** [bigtreetech/BIGTREETECH-TFT35-V3.0#2]
Do you intend to publish source files allowing customisation ?

**Comment by kordris** [comment]
I would like to know this also. because as it is now.. I can't use the touch screen part on my flyingbear tornado because it has two extruders. I use the second extruder mostly. So... I can't setup the screen for using two extruders. I have look everywhere for a update or something to update this screen so I can enable the second nozzle.

**Comment by thisiskeithb** [comment]
Or @Msq001? It would be really nice to be able to fix/customize this firmware.

**Comment by Mistergrow** [comment]
@bigtreetech Hello?Answer please

**Comment by spilz87** [comment]
@bigtreetech Hello?Answer please

**Comment by bigtreetech** [comment]
will released next week. maybe Tuesday or Wednesday

**Comment by spilz87** [comment]
Very good news :)

Thanks

**Comment by Patag** [comment]
Thanks

**Comment by Baltazart** [comment]
Un grand Merci.......

**Comment by Aleks-MO** [comment]
@Bigtreetech Will WiFi work on TFT35v3.0 when?

**Comment by bigtreetech** [comment]
@Aleks-MO we will implement it this week. ^_^

**Comment by p1ngb4ck** [comment]
@bigtreetech : got some (bad) experiences with the old module-type on a different printer (MKS-Gen-L, MKS TFT v4.0 + MKS WiFi). The idea behind that setup is basically the same. Can you maybe answer some questions I got towards the wifi function in general / confirm my assumptions ?
- Wifi is realized via "typical" wifi to serial connection I assume ?! - so probably available in tft serial mode only? Or will the serial connection from the wifi to the skr (1.3 in my case) will work in 12864 mode too, as long as the serial cable is connected?
- I managed to get connection via tcp <ip-address>:<port> in pronterface and use single gcodes (e.g. start abl) - but actually never achieved to print via wifi - it always stopped after few lines of gcode of the file I wanted to print - do you have the option to test the wifi-connection with repetierserver ? I`d offer to do betatesting if needed, I *think* I got the necessary background for that.
- can you maybe give me a heads up about the differences between ESP-01 and ESP-01S ? I mean technically? TY :)  :+1:

**Comment by spilz87** [comment]
Sources files shared !!! :)
Thanks @bigtreetech

**Comment by Patag** [comment]
Where ? Can't find them

**Comment by extesy** [comment]
@Patag https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

**Comment by Patag** [comment]
Thanks @extesy 
Can I close this one ?

**Comment by Patag** [comment]
I hope @spilz87 will open a new topic with his very pertinent questions

**Comment by spilz87** [comment]
@Patag you will find my new topics in firmware repository as I worked on TFT24 V1.1 ^^
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues
