### ISSUE TITLE
Mks Gen L Btt tff35 e3 v3 

### ISSUE THREAD

**Issue by Beaker1168** [bigtreetech/BIGTREETECH-TFT35-V3.0#30]
I am needing guidance. I have hooked up via teaching techs video with it not working, when I updated to the latest firmware I then lost some of the icons was just a blank squares. Is there something that I need to do to Marlin? I am on an Ender 3 with Marlin 1.1.9

**Comment by missMoshie** [comment]
Sounds like you forgot to add the folder for the icons.

**Comment by Beaker1168** [comment]
I have made sure I have added the folder to the Sd card each time, have tried both the unified and other both are given me issues.

Doug

**Comment by Spidermakercnc** [comment]
Hi me if you want I can help I have your configuration and my tasks very well only the wifi I can't make it work

**Comment by Spidermakercnc** [comment]
Hi me if you want I can help I have your configuration and my tasks very well only the wifi I can't make it work

**Comment by Clowntrigger** [comment]
See my reply at [Issue 430](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/430#issuecomment-604664793).

You need to either rename the bmp files to the correct names or compile the latest firmware and install it. 

> I have made sure I have added the folder to the Sd card each time, have tried both the unified and other both are given me issues. Doug
> […](#)
> Sent from my iPhone
> On Feb 4, 2020, at 18:11, zelpha ***@***.***> wrote: ﻿ Sounds like you forgot to add the folder for the icons. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by oldman4U** [comment]
Hello Beaker1168.

Could you please close this ticket in case you do not need it anymore.

Thank you

**Comment by Beaker1168** [comment]
Sorry not closing this earlier, not sure how but the 4th time was the charm and it all seems to be working now. thank you all of the help.
