### ISSUE TITLE
BTT TFT35 V3.0 Ramps 1.4 White screen after some time

### ISSUE THREAD

**Issue by wvabrinskas** [bigtreetech/BIGTREETECH-TFT35-V3.0#31]
I have installed the latest version of the firmware and I can't for the life of me get the screen to stay on or remain functional. It seems that after sometime the screen will just turn white and remain that way even after a reset. 

#### Diagrams
I have the screen plugged into the proper spot like this : ![](https://i.imgur.com/qWf8eua.jpg) and the EXT cables plugged in like this: ![](https://i.imgur.com/QlO4UUd.jpg)

#### Help
After attempting to start a print with an SD card it will start the process and then eventually just turn white and die. You can hear the buzzer go off every time to you tap the screen so there's something happening. Any suggestions?

**Comment by wvabrinskas** [comment]
## Marlin 2.0.x config
`#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`
`#define SERIAL_PORT 0`
`#define BAUDRATE 250000`

**Comment by Scope666** [comment]
One idea, try recompiling with baud at 115200 instead of 250000.  On mine I had bugs at 250000, no idea why.  ( I have increased buffers in my config )

It's in a few places, top of configuration.h and also in platformio.ini

**Comment by wvabrinskas** [comment]
> One idea, try recompiling with baud at 115200 instead of 250000. On mine I had bugs at 250000, no idea why. ( I have increased buffers in my config )
> 
> It's in a few places, top of configuration.h and also in platformio.ini

@Scope666 I compile with the arduino IDE, what buffer setting are you changing in the configuration.h?

**Comment by Scope666** [comment]
This is what I've been running for awhile now, they're actually the defaults now for my board.  (SKR Mini E3 v1.2)

![image](https://user-images.githubusercontent.com/31927547/73806805-8af2f200-4798-11ea-819e-9a1d50981a2a.png)

**Comment by wvabrinskas** [comment]
> This is what I've been running for awhile now, they're actually the defaults now for my board. (SKR Mini E3 v1.2)
> 
> ![image](https://user-images.githubusercontent.com/31927547/73806805-8af2f200-4798-11ea-819e-9a1d50981a2a.png)

Oh excellent thank you! Will give this a try. Just a heads up this in the `configuration_adv.h` file

**Comment by Scope666** [comment]
Yes, sorry I forgot to mention where it was.  Remember the switch to 115200 is the important bit.  There's some weird interaction between the TFT and the SKR that causes issues for me at 250000.  It's worth a shot.

**Comment by wvabrinskas** [comment]
So i tried this and the buffer stuff, 115200 seems to be the right baud rate, however the second i plug the SD in the screen goes white. Any ideas? it seems that the serial is busted?

**Comment by Scope666** [comment]
What if you place a gcode file on a USB stick, and try to print it from the TFT, does that work?

Also maybe updating to the latest version of the TFT firmware, just to see if that changes anything.  There's been a lot of development / bug fixes recently.

**Comment by wvabrinskas** [comment]
yeah ive updated as of yesterday. i'll double check and ill try USB

**Comment by wvabrinskas** [comment]
@Scope666 no go. Updated, even got a new screen. It seems to be happening even more frequently now.

**Comment by wvabrinskas** [comment]
So this is very odd. Plugging in the arduino mega to a raspberry pi running octo print and using an SD card on the BTT TFT35 worked....... the pi isn’t even connected to the printer through octopi serial. Wonder if it’s a power thing

**Comment by wvabrinskas** [comment]
For anyone with this issue when using RAMPS 1.4 and an Arduino Mega, it is absolutely a power issue. The 5V rail on the supplied through the TFT port on the RAMPS is not enough and will drop out after a while. I solved this by plugging in the Arduino Mega through the USB port into a 5V wall transformer. Haven't had issue yet. 

Another thing to note: 
If you plan on controlling the printer via octoprint and plug in the serial cables via the wifi UART port on the BTT TFT35 If you plug it in to the Octopi and try to connect via UART you will run into a MIN_TEMP issue with one of the sensors as Octopi is reporting an inaccurate temp on the same bus as the TFT.
