### ISSUE TITLE
Huge potential, why so sketchy

### ISSUE THREAD

**Issue by BtreeEnderPalette** [bigtreetech/BIGTREETECH-TFT35-V3.0#33]
Maybe I'm technologically spoiled but I find the systems unbearably unstable at times. I'm up to hire someone to produce software that does the printer justice. 

Maybe if we get enough willing votes we can solve the annoying little issues if BTT doesn't consider it necessary

**Comment by oldman4U** [comment]
Hi. 

What is the status of the privat development?

**Comment by BtreeEnderPalette** [comment]
There seems to have been much progress since I recently blew the thin dust layer off my printer.
