### ISSUE TITLE
Problem with BIGTREETECH TFT35 V3.0

### ISSUE THREAD

**Issue by Yotuntomatov** [bigtreetech/BIGTREETECH-TFT35-V3.0#35]
Hello, I have a problem with the BIGTREETECH TFT35 V3.0.
BIGTREETECH TFT35 V3.0 in 12864LCD mode works without problems. In Touch screen mode, it constantly freezes, “unknown command M10 =”, “unknown command M105” and other errors that occur on any action from the screen are written on the screen. the seal hangs almost immediately and these errors pop up. Firmware for the latest version did not produce an effect.
Did you have the same problems, and how did you solve them? Thank you and sorry for my English.

**Comment by Yotuntomatov** [comment]
TFT 35 ussed with SKR 1.3

**Comment by nocturnalit** [comment]
I'm having the same problem, running SKR mini e3 1.2 and tft35 v3.0 (with firmware V3.0.25.3) the problem did not occur before updating firmware. I think it was previosuly running a November release.

**Comment by fenix8k** [comment]
Same problem here skr 1.4 turbo, yesterday it was working fine, today I print a K calibration code, after 2 of them this start to happen

**Comment by compositecrafters** [comment]
I have the same problem with the mini E3 board and TFT35 E3 V3 combo
screen stuck on Marlin or BigTree color mode! I mean stuck, stuck after updating to TFT35 E3 V3.0.26 stuck stuck, non respondooo!  tried several flashes still stuck
but the factory board works perfect, its like the TFT35 E3 V3 has a major Bug!

**Comment by oldman4U** [comment]
Hi.

Has someone of you seen the reports regarding the metal frame touching the PCB of the TFT which can cause any kind of issue. Please check.

Thank you

**Comment by oldman4U** [comment]
@Yotuntomatov 

Could you please let us know the status of the reported issue.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by Yotuntomatov** [comment]
I apologize for not answering, I didn’t know to close the question. The problem has been resolved. The error occurred due to a poor quality loop. After replacing the loop from another screen, everything works.
