### ISSUE TITLE
Issue with printing from SKR mini E3 V1.2 on board SD card

### ISSUE THREAD

**Issue by Dimitar-88** [bigtreetech/BIGTREETECH-TFT35-V3.0#36]
Hello guy's
I have and odd experience. The TFT35 V2 i have sees the on-board SD card of my SKR Mini E3 V1.2.
The issue is after i select a file to print i am taken to the screen to monitor the print but everything on the display side stops working let me put some colour to what happens:  
1.Display timer Starts counting. (that works)
2. Bed and Nozzle temps show 26/0 28/0 ( basically close to the room temp) The requested values do not get there and the actual never updates
3. Printer starts to heat up performs G28 and G29 accordingly and starts to print 

If i try and cancel the print the screen freezes and displays " Loading" and remains there.

I have  #define SDCARD_CONNECTION ONBOARD  (set)
and     #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER 

Before attempt to print i can manipulate all settings and the display works fine. have not tested to print from USB  or from LCD SD slot.

Everything works fine if i use the simulated graphical display.

**Comment by jafc76** [comment]
I have exactly the same problem. It only happens if I'm on touchscreen mode. If I use the 12864 mode it works fine.

**Comment by Bankinghelp** [comment]
@bigtreetech I have the exact same issue need fix now, very important!!!!!!!!!!

**Comment by adzhsv** [comment]
I am also experiencing the exact same problems, Fan also stays at 0%

**Comment by Bankinghelp** [comment]
@adzhsv @jafc76 @Dimitar-88  I have got the fix! Just change your #define SERIAL_PORT_2 to 0 in Configuration.h and #define SERIAL_PORT to -1!!! Problem solved ^^. Infinite loading isn't a problem, it's just that it has to reach max temperature until it cancels the print, so wait until then and it will stop loading! Hope this was useful!

**Comment by Dimitar-88** [comment]
@Bankinghelp Setting up the SERIAL_PORT_2 to 0 is not possible !!! . The compiler throw's error.
In marlin firmware it is described that for MCU STM32F1 it is not allowed for Serial_port and Serial_port 2 to be of value 0.  
p.s. If i change the serial port 2 from 2 the TF35 fails to connect to the board at all.

**Comment by Dimitar-88** [comment]
@jafc76 @adzhsv @Bankinghelp  Just get latest firmware release 25.2 it fixed it for me

**Comment by adzhsv** [comment]
I still have this issue, I have the latest Firmware for the Both the SKR Mini and TFT35 v3.0

I have also tried changing the serial port, Then screen tells me No Printer Attached.

??

**Comment by Dimitar-88** [comment]
@adzhsv I used Serial Port = - 1, Serual Port 2 = 2. And note in my first post both #defines are needed as far as i know.  When canceling the print you need to wait till last command finishes, but that's ok.

**Comment by TheMiguelBi** [comment]
I'm also stuck here. 
Inserting a switch would cause the capacitors to remain charged.... 🤔
