### ISSUE TITLE
Knob LED color

### ISSUE THREAD

**Issue by Testmangh** [bigtreetech/BIGTREETECH-TFT35-V3.0#37]
The LED doesn't keep its state/color after restart... Its state should be saved inb the EEPROM and restored after turning the TFT board on.

**Comment by GeminiServer** [comment]
https://github.com/GeminiServer/BIGTREETECH-TouchScreenFirmware.git

Here you’ll find my version with knop led persistence support and also other improvements.

**Comment by Testmangh** [comment]
Thanks!
