### ISSUE TITLE
White Icons

### ISSUE THREAD

**Issue by ntedrow** [bigtreetech/BIGTREETECH-TFT35-V3.0#39]
On latest update on ready screen some icons are plain white with no information other than a percentage.

**Comment by oldman4U** [comment]
Hi.

What is the status of this issue. Have you been able to solve it by updating the bmp's?

Please let us know

**Comment by oldman4U** [comment]
@bigtreetech Could you please close this unused ticket

This could help new users find tickets which already cover their topic.

Thank you

**Comment by ntedrow** [comment]
I'm sorry, I completely forgot about this ticket. I was able to get the tft working.
