### ISSUE TITLE
12864 Mode not responding

### ISSUE THREAD

**Issue by rlvanhuis** [bigtreetech/BIGTREETECH-TFT35-V3.0#4]
What are the recommended Marlin 2.0 settings for the SKR Pro?
TMC 5160 SPI drivers installed.
I have tried several different 12864 code segments.  The emulated 12864 screen does not populate with any information.
Performed both hot boot and cold boot.  Same result.

**Comment by jeremiahhale** [comment]
I'm getting similar results as @rlvanhuis is getting in testing the new FTF35 3.0... I've found that 12864 mode works with SKR 1.3 but not with the SKR PRO 1.1 board. Making matters worse TFT Touch does not work on either board. I've reflashed the latest firmware BIGTREE_TFT35_V3.0.21.bin and I'm running the BigTreeTech Version of Marlin on the SKR Pro 1.1 Board.

**Comment by bigtreetech** [comment]
LCD12864 mode need set `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` in Marlin

**Comment by extesy** [comment]
@bigtreetech what mode in Marlin should be set if TFT35 is used as a touch screen?

**Comment by Mistergrow** [comment]
In Touch Mode you connect with serial so activate a serial Port in Marlin FW.

**Comment by bakaufman** [comment]
rlvanhuis, ever get this figure this out? same problem on GTR

**Comment by chronowerxs** [comment]
Has anybody found the solution for that issue?

**Comment by bakaufman** [comment]
For me it was a bad screen. Second screen sorted it out. Returned first to amazon.

**Comment by rlvanhuis** [comment]
No, got frustrated with the lack of response.  Shelved it hoping someone
might have working program after a year or so.  The latest v25 has comm
issues.  The printer stutters (SKR PRO V1.1) when connected over usb.
Right now just working over usb.
Thanks for asking.

**Comment by ebraiman** [comment]
For SKR Pro V1.1 I created a video that should apply, https://youtu.be/9i3Ee6UtC-Q .

**Comment by cengizceka** [comment]
skr 1.4 turbo board I tried everything, the result is the same problem continues, is there anybody who can solve this problem ???

**Comment by ebraiman** [comment]
@cengizceka This might help ... https://youtu.be/v0PCzHGXTgk

**Comment by oldman4U** [comment]
If someone has still issues connecting the TFT. Please go to the TFT firmware repository, read the ReadMe there and post a ticket if there is still a problem.

Thank you

Owner of this ticket 
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by rlvanhuis** [comment]
No longer need this ticket
