### ISSUE TITLE
SKR E3 1.2, TFT35-E3 v3.0 LCD Marlin Mode Scrabled Screen

### ISSUE THREAD

**Issue by wdjones23** [bigtreetech/BIGTREETECH-TFT35-V3.0#40]
Looking for some help with skr 1.2 E3 TFT35-E3 v3.0 Ender5. Everything looks good on boot but when I heat it up and start moving the xyz axis the screen scrambles in marlin mode. Any ideas?

![20200302_201941](https://user-images.githubusercontent.com/61296156/75933938-37cc9780-5e49-11ea-89ab-6eb521443814.jpg)
![20200302_200532](https://user-images.githubusercontent.com/61296156/75933971-43b85980-5e49-11ea-82ca-45b52e1171fd.jpg)

**Comment by rc8181** [comment]
Having the same problem, did you find a solution?

**Comment by oldman4U** [comment]
Hi.

Have you tried to use full screen mode? This works for me.

**Comment by rc8181** [comment]
I did, and it didn't work for me. I ended up changing the board from the
mini e3 to the v1.4 turbo and it works fine.

**Comment by wdjones23** [comment]
I found that it was a power supply issue. Changed to a Meanwell and
everything works as it should.

**Comment by oldman4U** [comment]
Hello wdjones23

Could you please close this ticket. Seems the reported issue has been solved in the meantime

Thank you

**Comment by oldman4U** [comment]
@bigtreetech Could you please close this ticket

This could help new users find tickets which already cover their topic.

Thank you
