### ISSUE TITLE
Upgrading to BIGTREE_TFT35_V3.0.25.3.bin won't change in Marlin mode.

### ISSUE THREAD

**Issue by PapiOrso** [bigtreetech/BIGTREETECH-TFT35-V3.0#44]
Reloading V3.0.25.2 works correctly. Does it happen to you too?

**Comment by cyberaxcess** [comment]
It works for me, but the dial doesn't change the selection, you have to touch the option you want (I'm sure this worked properly in V3.0.25.2).

**Comment by PapiOrso** [comment]
Thanks your solution works. I'm dumb, I hadn't thought of that. :-)
