### ISSUE TITLE
echo: error unknown command ever 3 to 5 mins 

### ISSUE THREAD

**Issue by carl5765** [bigtreetech/BIGTREETECH-TFT35-V3.0#49]
im getting a echo error message every 3 to 5 min it beeps and message reads 
unknown command: "m73 p8 r220"
and 
m73 q8 s227
m73 p8 r221
m73 q1 6 s205 
help 
running skr 1,4 tmc2009 tft3.5 v3

**Comment by oldman4U** [comment]
HI carl.

Would it be possible, that you use an extension in your slicer software, to show the layer high or progress?

This could eventually cause this issue.

**Comment by oldman4U** [comment]
Hi,

Any news regarding the reported issue.

Could you please close this ticket in case you do not need it anymore

Thank you

**Comment by Dingo1971** [comment]
I'm having the same issue, every so often ( 30 seconds to 2 minutes, varies) I get the same error message: see img below.
I know the M73 command is for print progress, 
I can't find anything in my slicer's setting that would make this happen.
I use PrusaSlic3r 2.2.0.
Any suggestions would be appreciated.  Thanks

![echo_error](https://user-images.githubusercontent.com/68745587/88406488-c2814500-cd9e-11ea-951b-da5780b6b349.jpg)

**Comment by oldman4U** [comment]
Check the gcode file itself.

 In Cura this is a script which has to be activated to see the layer number on lcd screen.

**Comment by Dingo1971** [comment]
Thanks, I read through the gcode files and see an M73 line every so often,, 
But I cant find in Prusaslicer where to turn that on or off.
I'll have to do some more research on Prusa slicer.
Thanks for the help!!!

**Comment by oldman4U** [comment]
👍🏻But carl seems to be a lazy guy. ;-)

@carl5765   Please close this ticket. Thank you

**Comment by Dingo1971** [comment]
HI all, 
Just wanted to post an update, and I figured out where the extra Gcode was coming from in PrusaSlicer., for anyone else that may need to know.
It;s under PRINTER SETTINGS->GENERAL --FIRMWARE ---SUPPORTS REMAINING TIMES  un-check this option to kill the extra Gcode.
![Untitled-1](https://user-images.githubusercontent.com/68745587/88472403-60305d80-cee0-11ea-9ba4-a1210e0fd10a.jpg)

**Comment by oldman4U** [comment]
Hi dingo. 

Great you found it. No idea if carl still watches his own ticket.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by Dingo1971** [comment]
> Please help the community and close the ticket once you do not need it anymore. Thank you

Sorry to be ignorant, but how do I close the ticket?

**Comment by oldman4U** [comment]
Hi @Dingo1971. You are ok. Carl is ignorant and is the only one who can close this issue. Please delete your replies here to get no notifications any more. Thank you and sorry that I bothered you🥺

**Comment by Dingo1971** [comment]
no worries,, is there away to keep my solution available so that others with the same issue can find it?

**Comment by oldman4U** [comment]
It would be great if you could start a new ticket under the general TFT firmware repo describing the problem and the solution. This would make this information available not only for users of this particular TFT. THANK YOU 👍🏻

**Comment by oldman4U** [comment]
@carl5765 

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by carl5765** [comment]
> 👍🏻But carl seems to be a lazy guy. ;-)
> 
> @carl5765 Please close this ticket. Thank you

lazy guys thanks great support answer

**Comment by carl5765** [comment]
> 👍🏻But carl seems to be a lazy guy. ;-)
> 
> @carl5765 Please close this ticket. Thank you

ilazyzt your just plane rude

**Comment by carl5765** [comment]
smart ass
