### ISSUE TITLE
request : invert "settings" and "leveling" icon

### ISSUE THREAD

**Issue by spilz87** [bigtreetech/BIGTREETECH-TFT35-V3.0#5]
"leveling" icon on home menu is at the same place than "back" in sub-menu, so when I click too much on back, the printer run a leveling :(

on my TFT2.4_1.1 as we have the source code, I invert both, but for the TFT3.5 V3.0 I can't :(

other people would like to invert them ?

thanks for you reply and/or help

**Comment by p1ngb4ck** [comment]
fw will be provided by btt soon as it is stated on the other issue thread

**Comment by spilz87** [comment]
now we have source code,
I switched it in my fork
if Im the only one who want this switch, I can close this issue :)
