### ISSUE TITLE
LCD Screen knob turns in wrong direction

### ISSUE THREAD

**Issue by Bamapaul** [bigtreetech/BIGTREETECH-TFT35-V3.0#50]
Just installed and updated firmware. The knob in marlin mode turns the selector in the opposite direction as all my other printers. I cannot seem to figure out why. Any thoughts?

**Comment by BobP2020** [comment]
This is configured within the Marlin firmware so you can change direction for menu select and increase/decrease direction

**Comment by Bamapaul** [comment]
Is it in the printers firmware or the TFT screen  Sent from Mail for Windows 10 From: BobP2020Sent: Sunday, May 10, 2020 10:25 AMTo: bigtreetech/BIGTREETECH-TFT35-V3.0Cc: Bamapaul; AuthorSubject: Re: [bigtreetech/BIGTREETECH-TFT35-V3.0] LCD Screen knob turns in wrong direction (#50) This is configured within the Marlin firmware so you can change direction for menu select and increase/decrease direction—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Bamapaul** [comment]
Found it! Thanks! That was waaayyyy too easy!
