### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by seanander** [bigtreetech/BIGTREETECH-TFT35-V3.0#58]
hooked up screen, get the choose menu but nothing happens except when i touch the screen the touch screen menu flashes on screen then goes back to the menu choose screen.

**Comment by oldman4U** [comment]
Hi.

There are other users having issues with their screens in case the PCB of the screen touches the metal frame of the printer.

Hope this helps

**Comment by oldman4U** [comment]
Hi.

Could you please let me know the status of the reported issue

Thank you

**Comment by seanander** [comment]
Oh sorry been working a lot lately but yea I put rubber spacers in and it
worked

**Comment by oldman4U** [comment]
Glad i could help. Could you please help me and close this ticket. Thank you
