### ISSUE TITLE
Print freezes when changing speed or flow

### ISSUE THREAD

**Issue by Whiskaya** [bigtreetech/BIGTREETECH-TFT35-V3.0#72]
I've had several instances when, while tuning speed or flow, suddenly the numbers go haywire and get scrambled (ONLY the flow/speed numbers), jumping randomly.
A few seconds later, the nozzle stops and stays hot, but doesn't move anymore.
Can't pause/resume, only stop print and start everything from the top.
All of this is in TFT mode. Haven't been able to try it in Marlin mode yet, as the screen gets scrambled as soon as I move the steppers or start preheating.

Ender 5
TFT35 E3 V3.0
SKR Mini E3 V2.0
Stock PSU

**Comment by oldman4U** [comment]
Hi.

This issue is fixed in the latest version of the TFT firmware.

Please try and let us know if you need any help

**Comment by Whiskaya** [comment]
It came with V3.0.26 from factory, and already had some configuration changes like Marlin mode not showing the title bar.

Still, had some problems/bugs, so I downloaded fresh firmware from Github. It was the same V3.0.26. This was 2 weeks ago.

Today I noticed the firmware was re-uploaded 8 days ago. Is that file corrected, even though it is the same version number?

**Comment by oldman4U** [comment]
Forget the version number, use the v26 from today and enjoy even the new
image preview when using Cura as the slicer.

It is great and your problem will also be fixed.

Happy printing

Whiskaya <notifications@github.com> schrieb am Di. 21. Juli 2020 um 14:39:

**Comment by Whiskaya** [comment]
Indeed, it's working fine so far. Thanks!

**Comment by oldman4U** [comment]
Also for me.

👍🏻

Whiskaya <notifications@github.com> schrieb am Mi. 22. Juli 2020 um 01:47:
