### ISSUE TITLE
TFT35 Encoder knob sets speed no matter which screen you're looking at

### ISSUE THREAD

**Issue by leopshef** [bigtreetech/BIGTREETECH-TFT35-V3.0#76]
The encoder knob changes the speed value when turned, meaning if you use the encoder knob to set your temperature value for example then the speed is also changed.

**Comment by oldman4U** [comment]
Yes. And because of this BTT turned off the ability to use the knob while using the touch screen, but users complained so BTT turned it on again. I am not sure there is a good solution for this which works for all users.

**Comment by leopshef** [comment]
It's fine for it to work, however it shouldn't change the speed when I'm using it to control what my temperature is.
If I'm on the set Hotend temperature screen, and I twist the encoder to change my temp to 240c, when I go back to the homescreen my speed is 200%. 
Is there no way to have the speed only update if the speed screen, or even speed/home screen is the one selected?

I'm not sure why people need to be able to change speed by default anyway tbh

**Comment by leopshef** [comment]
Sorry, I know why they need to change speed, but I don't know why the encoder's default behaviour is controlling speed.

**Comment by oldman4U** [comment]
It seems that there is no way to enable the knob without sending the pulses
also to Marlin, even the touchscreen is active. Check the closed tickets
related to this.

leopshef <notifications@github.com> schrieb am Di. 25. Aug. 2020 um 21:55:

**Comment by oldman4U** [comment]
In Marlins main window you control the speed with the knob. Because of this
you change the speed and not something else.

leopshef <notifications@github.com> schrieb am Di. 25. Aug. 2020 um 21:55:

**Comment by leopshef** [comment]
Ah that's a shame.
The encoder going to Marlin automatically controls speed then I assume.
I'll have a look around for other tickets related to this.

Thanks for getting back to me.

**Comment by leopshef** [comment]
Ah right, I understand.

Thank you!

**Comment by oldman4U** [comment]
You are welcome!

👍🏻
