### ISSUE TITLE
TFT35 v3 12864 Mode babystepping

### ISSUE THREAD

**Issue by ghost** [bigtreetech/BIGTREETECH-TFT35-V3.0#82]
Is there way to setup scale or step for babystepping in 12864 mode? Now I have step for Z offset item 1mm a I didn´t find, where can I set 0,1 mm or less.
Edit:
I mean during printing. If I want adjust first layer.

**Comment by infectedByte** [comment]
Menu->Movement->ABL->BabyStepping

**Comment by oldman4U** [comment]
Hi.

What is the status of the reported issue/question? Have you found a solution?

Please let me know

Thank you

**Comment by ghost** [comment]
The problem is solved. In Marlin file babystepping.c.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
