### ISSUE TITLE
nozzle park

### ISSUE THREAD

**Issue by Chad541121** [bigtreetech/BIGTREETECH-TFT35-V3.0#89]
I have the filament sensor plugged directly into the display and everything works great except, if I accidentally move the extruder position when changing the filament, then my print is messed up!  What do I need to do to lock the x, y, and z position until the filament is changed?

**Comment by oldman4U** [comment]
Hi. I recommend to close this ticket here and start a new one in the general tft firmware repository. It is software related and there are more users.

**Comment by Chad541121** [comment]
Moved to general tft section
