### ISSUE TITLE
no connection to the btt skr 1.4 turbo card

### ISSUE THREAD

**Issue by dacentichka** [bigtreetech/BIGTREETECH-TFT35-V3.0#91]
good day, I'm from Russia, I write via Google translator. I have a tft 35v3 and skr 1.4 turbo mode 12864 everything is good but in sensor mode the screen can not control the printer and says there is no connection, I tried all firmware screens ranging from 0.24 to 0.26, all Assembly Marlin for this Board, I tried to swap the ports and put a different speed in the firmware but it gave no result, but when I connect Reiterhof that appears on the screen temperature sensors and writes the printer ready. please tell me what to do?

**Comment by oldman4U** [comment]
Hi.

Please take pictures showing the cable and attach your Marlin and TFT configuration files here.

Thank you

**Comment by dacentichka** [comment]
> Привет.
> 
> Пожалуйста, сфотографируйте кабель и прикрепите сюда свои конфигурационные файлы Marlin и TFT.
> 
> Спасибо!

![photo_2020-11-10_00-42-45](https://user-images.githubusercontent.com/60215519/98600049-01a3b980-22ee-11eb-9a6d-de1099f17b6a.jpg)
![photo_2020-11-10_00-42-41](https://user-images.githubusercontent.com/60215519/98600059-049eaa00-22ee-11eb-9b3f-4da28290cb09.jpg)
![photo_2020-11-10_00-42-36](https://user-images.githubusercontent.com/60215519/98600065-07010400-22ee-11eb-9b85-a726bac615d7.jpg)
![photo_2020-11-10_00-42-32](https://user-images.githubusercontent.com/60215519/98600071-08cac780-22ee-11eb-95b4-ceedfe3f1068.jpg)
![photo_2020-11-10_00-42-28](https://user-images.githubusercontent.com/60215519/98600078-0a948b00-22ee-11eb-82b6-2626a23a730f.jpg)
![photo_2020-11-04_18-39-56](https://user-images.githubusercontent.com/60215519/98600081-0bc5b800-22ee-11eb-87fd-5b0b88490e0e.jpg)

**Comment by dacentichka** [comment]
[Uploading firmware_tft 35.zip…]()

**Comment by dacentichka** [comment]
[Uploading firmware_skr_1_4_turbo.zip…]()

**Comment by dacentichka** [comment]
> Привет.
> 
> Пожалуйста, сфотографируйте кабель и прикрепите сюда свои конфигурационные файлы Marlin и TFT.
> 
> Спасибо!

**Comment by oldman4U** [comment]
Problem solved?

**Comment by dacentichka** [comment]
> Проблема решена?

no, I didn't click this close button on my phone, I don't know English very well, I didn't know that this would close the question, and I don't know how to open it again

**Comment by oldman4U** [comment]
No problem! Your english is good enough.

Have you tested the cable before you extended it or do you have a second cable to test?

Please also make a picture which shows the problem "Printer not attached".

**Comment by oldman4U** [comment]
And when you upload something, please wait to press the "Comment" button until the Upload is finished.

Please upload the firmware again.

Thank you

**Comment by dacentichka** [comment]
> И когда вы загружаете что-то, пожалуйста, подождите, чтобы нажать кнопку "комментарий", пока загрузка не будет завершена.
> 
> Пожалуйста, загрузите прошивку еще раз.
> 
> Спасибо!

I'm still just learning to use github, I tested the wire, and I also tested the contacts on the boards with the wire in order to eliminate the pin breakage in the plug, everything is fine there, and I downloaded the firmware from your github, opened the skr 1.4 turbo folder in the visual Studio, checked the serial ports and clicked compile without changing anything else, since I'm just wondering how it works before I put it in a working printer, I can't put it on the printer until everything works as I need to print a lot

**Comment by dacentichka** [comment]
![Uploading IMG_20201105_005810.jpg…]()

**Comment by oldman4U** [comment]
<img width="1004" alt="Screenshot 2020-11-09 at 23 49 41" src="https://user-images.githubusercontent.com/54359396/98605766-43306680-22e6-11eb-88db-aeead72345cc.png">

I can not see the Uploaded files, only the first Pictures;-(

**Comment by dacentichka** [comment]
> <img alt="Screenshot 2020-11-09 at 23 49 41" width="1004" src="https://user-images.githubusercontent.com/54359396/98605766-43306680-22e6-11eb-88db-aeead72345cc.png">
> 
> I can not see the Uploaded files, only the first Pictures;-(

**Comment by dacentichka** [comment]
[firmware_skr_1_4_turbo.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/5514435/firmware_skr_1_4_turbo.zip)

**Comment by dacentichka** [comment]
![photo_2020-11-10_05-18-06](https://user-images.githubusercontent.com/60215519/98620015-7a6a3c00-2315-11eb-8a5b-a7abfcfdd31f.jpg)

**Comment by dacentichka** [comment]
I could not attach the entire folder of Marlin because it can not attach more than 10mb, I can send the entire archive to the mail

**Comment by oldman4U** [comment]
So the update was successful. Great. 

Can you navigate to Info and take a picture.

**Comment by dacentichka** [comment]
are you talking about the information in the minu on the display or in the information in the serial port on the M501 command?

**Comment by oldman4U** [comment]
First.

**Comment by dacentichka** [comment]
![photo_2020-11-10_21-24-15](https://user-images.githubusercontent.com/60215519/98715424-2dc94400-239b-11eb-8ba0-ff6be931668d.jpg)
![photo_2020-11-10_21-24-24](https://user-images.githubusercontent.com/60215519/98715428-2efa7100-239b-11eb-88fc-74ee3c927516.jpg)

**Comment by dacentichka** [comment]
> First.

so what's next?

**Comment by oldman4U** [comment]
Update to the most recent firmware. This is from April and there is one available from yesterday.

**Comment by dacentichka** [comment]
> Обновление до самой последней прошивки. Это с апреля, и есть один доступный со вчерашнего дня.

I'll try it now

**Comment by dacentichka** [comment]
> Update to the most recent firmware. This is from April and there is one available from yesterday.
I couldn't flash from the first folder, but from "Copy to SD Card root directory to update - Unified Menu Material theme" everything worked.

**Comment by dacentichka** [comment]
![photo_2020-11-10_22-34-50](https://user-images.githubusercontent.com/60215519/98725256-f4e29c80-23a5-11eb-8f59-f47c75820d25.jpg)
![photo_2020-11-10_22-40-05](https://user-images.githubusercontent.com/60215519/98725261-f613c980-23a5-11eb-8103-4fdb5a58d6bd.jpg)

**Comment by dacentichka** [comment]
![photo_2020](https://user-images.githubusercontent.com/60215519/98726394-80a8f880-23a7-11eb-8eff-29c8008b0fd8.jpg)

**Comment by oldman4U** [comment]
Make sure you have the following settings defined in Marlin:

#define SERIAL_PORT 0
#define BAUDRATE 115200

and also 115200 defined as Baudrate for the TFT under Menu-Settings-Connection-Baudrate

**Comment by dacentichka** [comment]
please tell me, and this should be viewed in the config.h or in config. adv. h? and another question, I tried to build the firmware for the screen myself, but it immediately gives an error when compiling that I don't understand, I took a screenshot of the error, tell me what to do please.
![IMG_20201111_192546_225](https://user-images.githubusercontent.com/60215519/98837833-7ee93e80-2454-11eb-8e81-bf03d38bca39.png)

**Comment by oldman4U** [comment]
The settings i wrote above are all in Configuration.h of your mainboard.

Can you compile other firmware. Looks like a problem with VSC/PIO. Rester VSC and see if this solves the problem.

**Comment by dacentichka** [comment]
should port "0" be port number one or port number two?

 I'll try to reinstall the VSC.

**Comment by oldman4U** [comment]
#define SERIAL_PORT 0

Like I wrote it, it can only be the first entry otherwise i would have written:

#define SERIAL_PORT_2 x

**Comment by dacentichka** [comment]
so I also tried, ie port 2 is commented out, and the serial port place -1 set 0, and also does not work

**Comment by oldman4U** [comment]
And the baud rate of mainboard and tft?

**Comment by dacentichka** [comment]
I tried everything possible, I will try today in 5 hours as I come home from work to reinstall vsc and compile the screen firmware myself.

**Comment by oldman4U** [comment]
You can change the baud rate of the screen in the TFT menu itself. No need to compile the firmware for this. After changing the baud rate, you have to wait 5-10 seconds for the new setting to take over.

**Comment by bttskrfan** [comment]
I have the same problem. I found that attaching SKR 1.4 Turbo to Creality Ender 5 LCD using EXP1 I get first Ender 5 logo then Marlin logo 2.0.6.1 and it gets stuck. TFT35 just keeps showing No Printer Attached and black screen when switching to emulator. Please advice.

**Comment by oldman4U** [comment]
Correct cabling could help.

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1047

[README.pdf](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/5532401/README.pdf)

**Comment by bttskrfan** [comment]
Sorry to interfere, I should have opened new issue, but since its related here is what I've managed to find out.

1. I've ordered SKR 1.4 turbo + TFT35 + tmc5610 from AliExpress on September
2. Default TFT firmware was April version
3. TFT35 was keep showing "No Printer Attached" error message
4. I've downloaded, built and updated SKR firmaware (2.0.6.1), but no luck
5. Then I've connected SKR to Ender 5 LCD to discover that SKR gets stuck at Marlin logo "2.0.6.1"
6. I went to Marlin and downloaded latest (2.0.7.2), Hooah! It works, but only with Ender 5 LCD. TFT35 still "No Printer Attached"
7. I've downloaded TFT35 firmware from May, Hooah! Connection established, but emulator still black screen
<I'm here now>
8. None of the latest precompiled TFT35 binaries works properly.
8a. The built has missing BMP files which exists, but uses wrong registry, so I had to rename all file names to be UPPERCASE, check this please.
8b. Touch functionality doesn't work with latest TFT35 binaries, the only version that works with me is May

 UPDATE: Thank you so much for the link @oldman4U

8b. Solved by placing empty reset.txt into root directory of sd card. After reboot it shows touchscreen calibration and it works

**Comment by oldman4U** [comment]
Send pictures which show the cabeling. 

Use self compiled firmware and let me know then.

**Comment by oldman4U** [comment]
Any news?

@bttskrfan So you have touchscreen but no Marlin Emulation? Send a picture which shows how the cables are connected between TFT and SKR.

**Comment by oldman4U** [comment]
@dacentichka 

Please reply or close this ticket.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
