### ISSUE TITLE
WIFI DID NOT WORK IN TFT 35 E3 V3

### ISSUE THREAD

**Issue by Talha909** [bigtreetech/BIGTREETECH-TFT35-V3.0#96]
I had SKR E2 V2 and bigtree tech e3 v3 tft screen. I also have ESP8266. I configure the ESP8266 and installed the esp into my tft screen. I connect the tft with the wifi. But i cant able to move my printer. Do i have to make any change in marlin.  Web software si working properly . but it did not accept the command. Do i need to change any thing in marlin.

**Comment by oldman4U** [comment]
Please close this ticket here. It is the wrong hardware.

Thank you

**Comment by oldman4U** [comment]
Please close this ticket now.
