### ISSUE TITLE
Does anyone know how to connect a k type thermocouple to the skr 1.4 turbo board using an adafruit amplifier?

### ISSUE THREAD

**Issue by jayala1213** [bigtreetech/BIGTREETECH-TFT35-V3.0#99]

**Comment by oldman4U** [comment]
Wrong repository. 

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by jayala1213** [comment]
> Wrong repository. 
> 
> Please help the community and close the ticket once you do not need it anymore. Thank you 

I'm sorry I'm fairly new to GitHub. What repository do you think I should put this on?

**Comment by oldman4U** [comment]
This is for the TFT 35 screen. You should use the SKR v1 repository.

jayala1213 <notifications@github.com> schrieb am Do. 10. Dez. 2020 um 05:57:

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
